### ISSUE TITLE
Check the issue with shifting of auto-markup 

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#108]
On test page 
https://jdi-testing.github.io/jdi-light/bootstrap-new.html
check when and how occurs  the shifting of elements' auto-markup.

**Comment by AlexeyGirin** [comment]
Маша будет переделывать механику накрытия

**Comment by MariiaNebesnova** [comment]
при запуске AutoFind:
- всем элементам на странице добавляется атрибут 'jdn-hash'
- выводится подсветка для предсказанных элементов, которые видны в окне
- при скролле или изменению размера окна выводится подсветка на вновь появившиеся элементы
- по кнопке Remove удаляются подствека и подписки на события
- при закрытии Dev Tools подсветка удаляется

**Comment by DaryaGurtovenko** [comment]
Version JDN 3.0.2 - ok
