### ISSUE TITLE
JDN: Define top level test scenarios

### ISSUE THREAD

**Issue by SSN-SPB** [jdi-testing/jdn#11]

**Comment by SSN-SPB** [comment]
The scope is defined within https://epam-my.sharepoint.com/:w:/r/personal/alexey_girin_epam_com/Documents/JDI/JDN/Testing/JDI-JDN_Test_Plan.docx? as follow:

1) Creating the manual tests and perform testing JDN plugin at test   page https://jdi-docs.github.io/jdi-light/  and for three subpages:    Home;    Contact form;    Metals & Colors;
2) Defining the list of required enhancement for JDI-JDN plugin
3) Creating the Automated Cucumber tests
4) Integrate Automated test into JDI CI/CD
5) Test JDN plugin at external pages
cc
@mf-code 
@WahlbergRu

**Comment by AlexeyGirin** [comment]
Done.
