### ISSUE TITLE
'Remove' button on 'Auto find' tab is available before/without results of Auto finding

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#115]
'Remove' button on 'Auto find Objects' tab is available before identifying as well as after the first pressing of the button after identifying - without any results. It can be problem because the clicking of the button gives (correctly) an error at Console.

**Preconditions:**
1 JDN plugin is installeded (since v.3.0).
2 The test page is available and opened. 
https://jdi-testing.github.io/jdi-light/index.html
3 The Developer console (F12) is opened 

**Steps to reproduce:**
1 Select JDN and open tab 'Auto find Objects'.
2 Click the button 'Remove'

**Expected result:**
The button is disabled.
As not bad option - button isn't presented at all before any results are exist. 

**Actual result:**
Button can be clicked and new error is occurs in Console tab.

**Steps to reproduce:**
3 Click 'Identify' button to find objects.
4  Click the button 'Remove'
5 Again click the button 'Remove'

**Expected result:**
The button is disabled.

**Actual result:**
Button can be clicked after results were cleared and an error is occurs in Console tab.

**Comment by AlexeyGirin** [comment]
Правила для исправления:
1. В любой момент времени должна быть активна одна кнопка и задизаблена вторая. При нажатии на активную кнопку (и при успешном завершении операции висящей на кнопке) - она должна дизаблиться и активной должнать становиться другая кнопка (напоминаю что у нас две кнопки - Identify и Remove)
2. Начальное состояние кнопок - Identify - активна и Remove - задизаблена
3. Система не должна позволять множественное нажатие на одну и ту же кнопку, но смена состояний кнопок должна откатываться на исходное если операция висящая на кнопке - не удалась и закончилась с ошибкой

**Comment by DaryaGurtovenko** [comment]
Verified on version JDN 3.0.2 (17 May's)
