### ISSUE TITLE
Two tables of Right block of test pages always aren't marked

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#120]
Test pages:
https://jdi-testing.github.io/jdi-light/dates.html
https://jdi-testing.github.io/jdi-light/dates.html
and all other pages of https://jdi-testing.github.io/

The issue is that those two tables - 'Log' and 'Result' which are presented on each test page - are almost never recognized as tables and marked. See screenshot:
![TablesBlock](https://user-images.githubusercontent.com/80756170/117763702-ee898c00-b233-11eb-81c1-c50c57d06b89.png)
Just couple of times I got the recognition of one of them - and no one for the second one.
![LogRes - ReFound](https://user-images.githubusercontent.com/80756170/117763850-2e507380-b234-11eb-83a8-2caf3827cd8c.png)
The 'Log' table contains text but even this cannot help with the issue.

**Comment by vfuga** [comment]
actually this is not a bug. These elements are not controls
