### ISSUE TITLE
Several links of Left panel of test pages with links are marked twice

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#121]
Test pages:

https://jdi-testing.github.io/jdi-light/simple-table.html
https://jdi-testing.github.io/jdi-light/metals-colors.html
and all other pages of https://jdi-testing.github.io/

The issue is that some of links of the panel with links list are **always** marked and labeled twice. See screenshots:
![DoubleSimpleTable](https://user-images.githubusercontent.com/80756170/117764750-abc8b380-b235-11eb-9158-476c3087a8bb.png)
![DoubleMetal](https://user-images.githubusercontent.com/80756170/117764751-ac614a00-b235-11eb-9a2a-62a1782a5fb9.png)

At first I thought it was due to the fact that they nested and can be expanded, but in fact, not - 'Table with pages' and Different elements' cannot be.
![StackedLinks](https://user-images.githubusercontent.com/80756170/117765090-209bed80-b236-11eb-897f-69b805932281.png)
The issue's repro is 100% and they're always the same links.

**Comment by vfuga** [comment]
These steps should help to get rid of most of bugs listed in this issue
@DaryaGurtovenko , could you check it out one more time?

docker login registry.gitlab.com                       # password will be asked 
docker run -p 127.0.0.1:5000:5000/tcp -ti --rm --name jdi-ml registry.gitlab.com/vfuga/jdi-qasp-ml

**Comment by DaryaGurtovenko** [comment]
Isn't reproduced on version 0.1-alt on any of test pages
