### ISSUE TITLE
Main area of 'Index' page of  test site is falsely identified as a link

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#122]
Test page:
https://jdi-testing.github.io/jdi-light/index.html

Reprorate of the issue is 100%.
On 'Index' page the whole area of central part of the page is marked and labeled as Link.
See please screenshot
![MainPFolseLink](https://user-images.githubusercontent.com/80756170/117766241-ed5a5e00-b237-11eb-9741-50fbdfed55f1.png)

**Comment by vfuga** [comment]
@DaryaGurtovenko , Даша посмотри пожалуста, вот так вот:

docker login registry.gitlab.com                       # password for gitlab will be asked 
docker run -p 127.0.0.1:5000:5000/tcp -ti --rm --name jdi-ml registry.gitlab.com/vfuga/jdi-qasp-ml

**Comment by DaryaGurtovenko** [comment]
Issue isn't reproduced on version 0.1-alt
