### ISSUE TITLE
Переделать существующие локаторы на локаторы по ID

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#132]
Текущие локаторы генерятся на основании наших собственных атрибутов которые имеют временный характер типа такого:
@UI("[jdn-hash]=6717128549243799650938835318") public Button button_6717128549243799650938835318;

Нужно переделать на локаторы по ID атрибуту.
Типа такого: 
@UI("[name='main-title']") public Label mainTitle;

В случае, если ID атрибута у контрола нет, то генерация этого контрола должна выглядеть примено так:
// @UI("NO ID FOR THIS CONTROL CONSIDER ANOTHE LOCATOR") public Label ????

**Comment by toshQA** [comment]
Verified in v.3.0.14. All defects will be fixed as part of the ticket https://github.com/jdi-testing/jdn/issues/176
