### ISSUE TITLE
Пробрасывать клик по элементу насквозь ко всем перекрывающимся элементам

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#139]
Сейчас некоторые элементы могут перекрывать другие не давай возможность их исключить из генерации.
Нужно сделать что бы клик по стеку из перекрывающих друг друга элементов доходил до каждого элемента в списке и выключал весь стек

**Comment by DaryaGurtovenko** [comment]
Verified, work just great!
