### ISSUE TITLE
Something is wrong w/Identify and Remove buttons

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#141]
1. Open https://jdi-testing.github.io/jdi-light/
2. Go to https://jdi-testing.github.io/jdi-light/bootstrap-new.html (via left side menu)
3. Press Identify button (wait till it ends)
4. Navigate to previous page by pressing Back button in browser navigation bar
5. Press Remove button
NOTE THAT Remove button remain ACTIVE (should be disabled)
6. Press Identify button
NOTE THAT both - Identify and Remove buttons become disabled. This is wrong.

------------------------------------------------------------------------------------------------------
The issue is extracted from closed #128.
State of plug-in is not changed after updating/refreshing/jump of the processed page so the 'new' page has the same one. 
Description #128:
> after using those 'Identify/Remove' buttons the state is changes but doesn't saved so 
if somehow the page is refreshed the mark-up is deleted but can be Identified again (with creating new lay without deleting the previous one so the button 'Remove' is blocked and markup cannot be cleaned. Both buttons are blocked now and the only way is to close page and plugin).

We need to have new 'State' variable, which will determine the state of the buttons.

**Comment by DaryaGurtovenko** [comment]
Verified on 3.0.12  -looks good
