### ISSUE TITLE
Кастомное контекстное меню для блоков покрытия

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#146]
В режиме покрытия (в обычно режиме этого не должно быть) при нажатии левой кнопкой мышы на блок покрытия должно появляться контектное меню со следующими пунктами:
- Name: %Block Name% > - #208 
- Block type: %Block Type% > - #230
- Remove block
- Switch [on | off]
- Bring to front -  #209
- Bring to background - #209

1. "Name: %Block Name% >" - clicking on this option opens change name dialog, 
2. "Block type: %Block Type%" hovering mouse over this option should appear additional list of types and let user to select alternative type of control (current time should be marked in the list by having check mark before proper type)
3. Remove block - simply removes this block from the screen
4. Switch on/off - change current state of block from "added to generation" to "removed from generation" (same functionality as it was implemented in #131). Current state should be reflected in option name. If block included to generation - menu option label should be "Switch off". If it is currently excluded - it should be "Switch on"
5. Bring to front - clicking on this option should bring this block on the front layer
6. Bring to background - clicking on this option should bring this block on the bottom layer

**Comment by MariiaNebesnova** [comment]
please, move following to new issues: 
1) change name
2) Bring to front/background

**Comment by DaryaGurtovenko** [comment]
Context menu: impossible to call up the menu after element's type change #233

**Comment by toshQA** [comment]
Undisplayed elements of context menu can not be selected [#234](https://github.com/jdi-testing/jdn/issues/234)

**Comment by toshQA** [comment]
Elements are no switched off after removing from context menu [#237](https://github.com/jdi-testing/jdn/issues/237)
