### ISSUE TITLE
JDN: Prepare the tests for https://jdi-testing.github.io/jdi-light/index.html Home  - FOR DECOMPOSITION

### ISSUE THREAD

**Issue by SSN-SPB** [jdi-testing/jdn#15]
Preparing JDN tests for Home page at https://jdi-testing.github.io/jdi-light/index.html

**Comment by SSN-SPB** [comment]
The set of created test cases is available as xls file at sharepoing https://epam-my.sharepoint.com/:x:/r/personal/alexey_girin_epam_com/Documents/JDI/JDN/Testing/JDN_testcases.xlsx?

**Comment by AlexeyGirin** [comment]
Done.
