### ISSUE TITLE
If some window is on top of the main one, the plugin stops working if try to autofind

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#150]
**'Steps to reproduce on test site:**

1 Open https://jdi-testing.github.io/jdi-light/performance.html page.
2 Open Developer console and jump to JDN tab.
3 Open 'Auto Find Objects' tab 
4 On page click on any of table cell, for example, (1,1) 'Burke Tucker'.
5 On Dev console click 'Identify' button

**Result:** 
Nothing happened, no messages or progress or anything
All buttons are disabled now.

**Expected result:**
Need to discuss:
should we return some message as 'First close the service window'
or
predict buttons on the top window.

The issue is reproduced on any pages with pop-up window

**Comment by texonth** [comment]
Проблема в том что браузерные алерты блокируют контент-скрипты.
Поэтому если просто нажать Identify при открытом алерте, потом закрыть алерт - элементы определятся когда джаваскрипт проснется.
Но если за это время состояние нашего интерфейса расширения поменяется - контент скрипты об этом не узнают, а значит возникнет рассинхрон состояний которые и приводят к блокированию кнопок и undefined behavior.

**Comment by DaryaGurtovenko** [comment]
ver. 3.0.34 - Message 'Script is blocked' is shown+
After window is closed the plugin works+
