### ISSUE TITLE
Сделать Auto Find Objects дефолтным табом при открытии

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#158]

**Comment by DaryaGurtovenko** [comment]
Last time Alexey asked to do the tab the first one. That's: chat part:
[04/06 11:13] Mariia Nebesnova
>     табу AutoFind может вперед вынести? или просто дефолтно открытой сделать?
[04/06 14:04] Alexey Girin
>     выноси вперёд, да
Need to discuss a bit.
On ver.3.0.8 the tab sits where it always was, but as expected it's opened as default.

**Comment by DaryaGurtovenko** [comment]
Just perfect.
