### ISSUE TITLE
Исследовать разницу распознования контролов в зависимости от того проматывалась ли страница до самого низа или нет

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#162]
[FirstIdentification.parquet.txt](https://github.com/jdi-testing/jdn/files/6596634/FirstIdentification.parquet.txt)
[FirstIdentification.json.txt](https://github.com/jdi-testing/jdn/files/6596635/FirstIdentification.json.txt)

[SecondIdentification.json.txt](https://github.com/jdi-testing/jdn/files/6596645/SecondIdentification.json.txt)
[SecondIdentification.parquet.txt](https://github.com/jdi-testing/jdn/files/6596648/SecondIdentification.parquet.txt)

1. Go to https://jdi-testing.github.io/jdi-light/html5.html page
2. Press Identify button
Note that system found only 29 controls available for generation.
![image](https://user-images.githubusercontent.com/26869421/120762838-4eb3db00-c51f-11eb-9a93-3cabb2ed8a27.png)

4. Press Remove button
5. Scroll this page down till end
6. Press Identify button again
Note that system found only 129 controls available for generation (hundred more!)
![image](https://user-images.githubusercontent.com/26869421/120763507-f5987700-c51f-11eb-97d9-6dc711fb71ae.png)

**Comment by AlexeyGirin** [comment]
@toshQA to re-check

**Comment by AlexeyGirin** [comment]
Надо решать на клиенте

**Comment by AlexeyGirin** [comment]
Вопспроизводится на других сайтах
@toshQA - добавь сайты где воспроизводится

**Comment by toshQA** [comment]
Сайты:
http://www.protesting.ru/
https://4pda.to/
https://www.drive2.ru/
http://tass.ru/

**Comment by AlexeyGirin** [comment]
Not repro any more

**Comment by toshQA** [comment]
https://habr.com/ru/top/daily/
https://github.com/

**Comment by toshQA** [comment]
Verified in v.3.0.20, works correctly.
