### ISSUE TITLE
Need to add # simbol before each IDs in generated files

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#168]
In fles which we generate on base of auto-found objects it's needed to be done the following change, see example below:

@UI("passportSeria") public TextField passportSeria; -> @UI("**#**passportSeria") public TextField passportSeria;

So we need to add # before each ID. It's needed for correct work of JDI part.

**Comment by toshQA** [comment]
Works correctly, checked in version 3.0.12
