### ISSUE TITLE
JDN:Not logged user is redirected back to Home page

### ISSUE THREAD

**Issue by SSN-SPB** [jdi-testing/jdn#17]
Not logged user is redirected back to Home page

Steps to reproduce:
1 Navigate to JDI testing home page https://jdi-testing.github.io/jdi-light/index.html by not logged user

Status: page is opened, the left menu frame is available:
Home
Contact form
Service (down arrow)
Metals & Colors 
Elements packs (down arrow)

2 Click 
Contact form https://jdi-testing.github.io/jdi-light/contacts.html
Metals & Colors  or https://jdi-testing.github.io/jdi-light/metals-colors.html

Expected: The corresponding page is opened and displayed

Actual: Immediately after opening user is redirected back to Home page https://jdi-testing.github.io/jdi-light/index.html 

i.e. pages 'Contact form' and 'Metals & Colors' are not available for not logged user
Remark: issue is not redirected for logged user 

cc
@RomanIovlev 
@mf-code 
@WahlbergRu

**Comment by Mariya-Z** [comment]
This bug is related to JDI testing site. JDN has no connection with it

**Comment by SSN-SPB** [comment]
Issue is reproduced 2020/07/30

cc 
@ViktarR
@WahlbergRu

**Comment by AlexeyGirin** [comment]
Not a bug.
In order to avoid redirection - you have to be logged in as Roman/Jdi1234
