### ISSUE TITLE
One more file is downloaded each time the button "Generate And Download" is clicked

### ISSUE THREAD

**Issue by toshQA** [jdi-testing/jdn#181]
**Preconditions:** 

- user installed JDN extension v.3.0.10 for Chrome Browser
- user opened JDN extension in chrome dev tools on tab "Auto Find Objects"

**Steps:**

1. Click on "Identify" button
2. Wait for finishing the process
3. Click on "Generate And Download" button
4. Click on "Generate And Download" button one more time

**Expected result:** only one file was downloaded

**Actual result:** two files were downloaded

**PS:** for the third time clicking 3 files will be downloaded

**Comment by DaryaGurtovenko** [comment]
Verified on 3.0.11/12
