### ISSUE TITLE
Plugin doesn't work with Incognito mode, even no tabs are shown

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#185]
The trying to open plugin in Chrome's Incognito mode absolutely failed, see please screenshot below:
![IncognPlugin](https://user-images.githubusercontent.com/80756170/122075002-62562000-ce02-11eb-8b4f-3d9d7f0954c2.png)
This is plugin's console output:
![IncognConsole](https://user-images.githubusercontent.com/80756170/122075179-8ade1a00-ce02-11eb-9df4-9c71853c09e8.png)
 
**Preconditions**
1 JDN is installed
2 JDN is allowed in Incognito, see instruction below:
2.1 Navigate to Extensions in Chrome (chrome://extensions).
2.2 In the new tab that opens, click 'Details' on JDN area ('Подробнее)
2.3 Click the “Allow in Incognito” button ('Разрешить использование в режиме инкогнито').

**Steps:**
1 Open Chrome in Incognito mode (for example, pressing Ctrl+Shift+N)
2 Open JDI in Dev console

**Result:**
The JDI tab exists in Dev console but doesn't contain any tabs or anything at all.

**Expected result:**
JDI looks as usual.

**Comment by AlexeyGirin** [comment]
Not a bug. Closed.
