### ISSUE TITLE
Does not identified elements on the page

### ISSUE THREAD

**Issue by toshQA** [jdi-testing/jdn#191]
**Preconditions:**

- User installed JDN extension v.3.0.10 for Chrome Browser
- Docker was run

**Steps:**

1. Open site "https://jdi-testing.github.io/jdi-light/performance.html"
2. Open chrome dev tools
3. Click on tab of JDN extension
4. Click on "Identify" button
5. Open chrome dev tools for extension 

**Expected result:** elements on the page are identified

**Actual result:** there is an error in browser console:

panel.html:1 Error handling response: TypeError: Cannot read property 'id' of undefined
    at chrome-extension://igjpiknckkbakhnnfepndcdbgabbcjlg/main.bundle.js:86978:21

<img width="647" alt="Screenshot 2021-06-17 at 11 09 51" src="https://user-images.githubusercontent.com/24373052/122358128-0653de80-cf5d-11eb-8881-ac85d574cee4.png">

**Comment by texonth** [comment]
Create a handler for errors when active tab id is not found for highlighting elements.
No more infinite loading in this case.

Still have a problem with active tab management - create issue #219

**Comment by toshQA** [comment]
Verified in v.3.0.19. See previous comment.
