### ISSUE TITLE
JDN plugin: checkbox ‘Generate & Download’. The pageobject.zip file is not downloaded automatically

### ISSUE THREAD

**Issue by SSN-SPB** [jdi-testing/jdn#20]
JDN plugin: checkbox ‘Generate & Download’. The pageobject.zip file is not downloaded automatically

Steps to reproduce (old design):
1 Navigate to https://jdi-testing.github.io/jdi-light/index.html and open the Developer console (F12)
2 Select JDN tab
3 Check the button 'Generate several Pages'
4 Within menu "Generate" click ‘Cogwheel’ button within 'Generate'Cogwheel' double button
5 Check checkbox ‘Generate & Download’
6 Ensure that ‘JDI Light’ is selected
7 Within menu "Generate" click ‘ArrowLeft’ button within  'ArrowLeft'Setting'  double button
8 Press the button 'Generate several Pages'
9 Check the list of downloaded files

Expected:
All generated files are downloaded automatically
Actual:
Generated files are not downloaded

cc
@mf-code 
@WahlbergRu

**Comment by Mariya-Z** [comment]
If you run the corresponding branch, check "Generate & Download" checkbox, and then Generate Several Pages, new test files for each page (.java) would be downloaded.

But in this case, pageobject.zip file should be downloaded automatically

**Comment by AkioFaris** [comment]
This https://github.com/jdi-testing/jdn/pull/50 PR fixed auto download with enabled checkbox when we click "Generate". However we still need to fix that for several pages page objects should be dowloaded in .zip archive.

**Comment by SSN-SPB** [comment]
Reproduced 2020/07/20
@ViktarR 
@WahlbergRu
