### ISSUE TITLE
При распознавании элементов на странице был найден атрибут DefaultClass, который не существует в JDI. Необходимо распознавать такие атрибуты как UIElement.

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#200]

**Comment by AlexeyGirin** [comment]
Not a bug, but lets keep it til #202 fix

**Comment by mikhnovich** [comment]
default class'ов не наблюдается, UIElement присутствует
![image](https://user-images.githubusercontent.com/69044248/125609571-e5b5625a-71d8-4348-9a94-0aa60dc467db.png)
