### ISSUE TITLE
[3pt][US-5-2] Проапдейтить мэпинг для новых возвращаемых моделью элементов

### ISSUE THREAD

**Issue by mikhnovich** [jdi-testing/jdn#202]
Сейчас названия контролов возвращаемые моделью меняются на красивые названия через мэпинг.
После выхода новой модели (которая только на Material UI)

Решили мэпинг убрать вообще совсем.

[Related US-5-2](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12877868/US-5-2+Recognition+of+elements+from+library+Material+UI)

**Comment by AlexeyGirin** [comment]
Получить полный список контролов у Славы и замапить его на списко контролов которые попадают в Page Object

**Comment by savinovava** [comment]
В связи с тем, что генератор не будет изменён, можно приступить к разработке
2 pt front + 2 pt QA 
1 pt front + 2 pt QA

**Comment by savinovava** [comment]
В JDI не у всех контролов есть свой класс 
Было проведено ревью, пока не влито в master
Нужно предоставить список контролов  @AlexeyGirin 
https://jdi-docs.github.io/jdi-light

**Comment by savinovava** [comment]
к MVP 17.12 договорились взять текущую имплементацию в документации
https://github.com/jdi-testing/jdn-ai/issues/151

**Comment by MariiaNebesnova** [comment]
3.0.104

**Comment by MariiaNebesnova** [comment]
3.0.106

**Comment by pulya-na-vullet** [comment]
<img width="434" alt="Снимок экрана 2021-12-22 в 8 59 03 AM" src="https://user-images.githubusercontent.com/61897393/147043165-5e759c57-5b21-497c-b7c1-75436c267786.png">
Версия в draft

**Comment by pulya-na-vullet** [comment]
JDN v 3.0.106
Back-end v 2021-12-22-14.54.53
Названия контролов корректные во время регресса проблем не обнаружено
