### ISSUE TITLE
Report Problem button

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#205]
Создать кнопку (назовём её Report Problem)
При нажатии на который открывается окно создания нового письма в аутлуке (ну или дефолтном постовом клиенте) к которому уже приаттачен архив содержащий следующую информацию: JSON + Screenshot + URL сайта
Поля должны быть заполнены следующим образом:
To: JDI-support+JDN@epam.com
Subject: Some elements were not identified on page: %URL%
Body: Hi,
Some elements were not identified on the page, please have a look.
\<Please save provided archive to disk and attach it to this email\>
\<PROVIDE ADDITIONAL DETAILS IF NEEDED\>

**Comment by AlexeyGirin** [comment]
mailTo: JDI-support+JDN@epam.com

**Comment by AlexeyGirin** [comment]
Помимо открытия шаюлона письма - давать на скачку архив с JSON + Screenshot

**Comment by Bryant-24** [comment]
В первой версии решили всё-таки отдавать скриншот и json-файл по отдельности (чтобы не тянуть библиотеку JSZip вместе с расширением).

**Comment by DaryaGurtovenko** [comment]
Now works as Ruslan described: two files are downloaded, window with instruction is opened, email is created. v3.0.30

**Comment by DaryaGurtovenko** [comment]
#269

**Comment by DaryaGurtovenko** [comment]
No defects or tasks for ver. 3.0.34.
