### ISSUE TITLE
Elements are not identified on vk.com

### ISSUE THREAD

**Issue by toshQA** [jdi-testing/jdn#206]
**Preconditions:**

- User installed JDN extension v.3.0.14 for Chrome Browser
- Docker was run

**Steps:**

1. Open site: https://vk.com/
2. Open chrome dev tools on "JDN" tab
3. Click on "Identify" button
4. Wait for successful result

**Expected result:** all elements on the page are identified 

**Actual result:** only 6 elements are identified

<img width="1680" alt="Screenshot 2021-06-22 at 11 20 34" src="https://user-images.githubusercontent.com/24373052/122889957-ee5cd000-d34b-11eb-8e9b-58152ed5959f.png">

**PS:** macOS, google chrome version 91.0.4472.106 (Official Build) (x86_64)

**Comment by AlexeyGirin** [comment]
Closed.
