### ISSUE TITLE
Squares of identified elements are scrolled with the page's content

### ISSUE THREAD

**Issue by toshQA** [jdi-testing/jdn#207]
**Preconditions:**

- User installed JDN extension v.3.0.14 for Chrome Browser
- Docker was run

**Steps:**

1. Open site: https://vk.com/
2. Open chrome dev tools on "JDN" tab
3. Click on "Identify" button
4. Wait for successful result
5. Scroll the page down

**Expected result:** squares of identified elements are on their positions

**Actual result:** squares of identified elements are scrolled

![Welcome! _ VK](https://user-images.githubusercontent.com/24373052/122891475-38928100-d34d-11eb-8f50-26af2b11389a.gif)

**Comment by DaryaGurtovenko** [comment]
I just want to add that we haven't seen this issue before, none of the team.

**Comment by MariiaNebesnova** [comment]
we have such example on test pages: 
- go to https://jdi-testing.github.io/jdi-light/complex-table.html
- run Idetify
- remove main highlight block from table and try to scroll it - you'll see this bug
- 
![image](https://user-images.githubusercontent.com/82033805/123602355-548c9b80-d801-11eb-82b3-691e7d015d75.png)


idea is that it's not a scroll of the whole page, it's a scroll of a certain container

**Comment by MariiaNebesnova** [comment]
Implemented functionality: on scrolling container highlight is being removed from it's scrolling content. On the plugin form appears message: "Prediction is not actual anymore." If user re-runs identification, will be highlighted content, that is currently visible in the container.

**Comment by toshQA** [comment]
Verified In v.3.0.36. Works correctly.
