### ISSUE TITLE
Change name feature

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#208]
Extracted from #146

Add capability that allow user change default element name to custom one from right-click context menu
UI could be vary but in my head it should be appeared Save/Cancel edit box

**Comment by mactopus** [comment]
https://www.figma.com/proto/kZswCb9WEvRPX4gUtzeGhs/JDN-8-July?page-id=0%3A1&node-id=17%3A68&viewport=257%2C493%2C0.08280636370182037&scaling=min-zoom&starting-point-node-id=17%3A68
прототип, там есть состояние изменения имени

**Comment by DaryaGurtovenko** [comment]
Verified on ver. 3.0.40
