### ISSUE TITLE
Several elements are grouped in one

### ISSUE THREAD

**Issue by toshQA** [jdi-testing/jdn#211]
**Preconditions:**

- User installed JDN extension v.3.0.14 for Chrome Browser
- Docker was run

**Steps:**

1. Open site: https://www.ozon.ru/category/smartfony-15502/
2. Open chrome dev tools on "JDN" tab
3. Click on "Identify" button
4. Wait for successful result
5. Scroll the page down

**Expected result:** all identified elements are consist of one element

**Actual result:** some identified elements are consist of several elements

<img width="1680" alt="Screenshot 2021-06-22 at 12 58 05" src="https://user-images.githubusercontent.com/24373052/122905415-e0ae4700-d359-11eb-8b65-f34e6d5c8043.png">

**Comment by AlexeyGirin** [comment]
Closed.
