### ISSUE TITLE
Checkboxes and radiobuttons are not identified on yandex.market and Wildberries

### ISSUE THREAD

**Issue by toshQA** [jdi-testing/jdn#213]
**Preconditions:**

- User installed JDN extension v.3.0.14 for Chrome Browser
- Docker was run

**Steps:**

1. Open site: https://market.yandex.ru/catalog--smartfony/16814639/list
2. Open chrome dev tools on "JDN" tab
3. Click on "Identify" button
4. Wait for successful result
5. Scroll the page down

**Expected result:** checkboxes and radiobuttons are identified

**Actual result:** checkboxes and radiobuttons are not identified

**PS:** reproduce on https://www.wildberries.ru/catalog/elektronika/igry-i-razvlecheniya/aksessuary/garnitury

<img width="1680" alt="Screenshot 2021-06-22 at 14 20 52" src="https://user-images.githubusercontent.com/24373052/122916621-c1b5b200-d365-11eb-96d0-e6757de09fca.png">

<img width="1680" alt="Screenshot 2021-06-22 at 14 25 14" src="https://user-images.githubusercontent.com/24373052/122916641-c712fc80-d365-11eb-9356-6c9fbfe42618.png">

**Comment by AlexeyGirin** [comment]
Ждём новую обучалку - потом посмотрим

**Comment by DaryaGurtovenko** [comment]
After discussion we decided don't use for testing sites which has own framework. 
So if the issue is reproduced on some small users' sites, we'll return to it.

**Comment by AlexeyGirin** [comment]
Решили закрыть т.к. сайт видимо защищаяется от автоматического парсинга своих страничек.
В реальной работе такого никогда не будет
