### ISSUE TITLE
Переделать координаты

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#217]
Сейчас используются клиентские координаты.
А надо использовать координаты странички.

Взаимодействуя со Славой добиться что бы результат распознования не зависил от того в какой части странички мы находимся.
Сейчас - на страничке https://jdi-testing.github.io/jdi-light/html5.html результат разные если мы распознаём в начале странички и если промотать по низа

**Comment by texonth** [comment]
https://github.com/jdi-testing/jdn/releases/tag/3.0.18

**Comment by AlexeyGirin** [comment]
Closed.
