### ISSUE TITLE
Active tab management issue

### ISSUE THREAD

**Issue by texonth** [jdi-testing/jdn#219]
To reproduce bug:

- Open page for testing
- Open JDN Panel and click Identify
- Open new tab
- After few seconds return to the page for testing and see Successful status at the panel but no highlights at the page.

It happens because extension tries to find active tab Id after every action. We need to store it after open JDI Panel or after click Identify and after that use saved Id for access to tab.

**Comment by DaryaGurtovenko** [comment]
Fixed - 3.0.21
