### ISSUE TITLE
Объединять радиобаттоны на стороне клиента

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#224]
Сейчас радиобаттоны определяются как отдельные элементы, хотя - их стоит объединить в один по атрибуту name.
Делать это стоит на стороне клиента в рамках шага постпроцессинга

**Comment by MarinaFm** [comment]
Проверено, в MUI отдельные радиобаттоны объединяются в один по атрибуту Radiobuttons
![image](https://user-images.githubusercontent.com/88709848/179356023-7552a90a-41eb-47dc-9f29-734a0e5fc11b.png)
