### ISSUE TITLE
[US-7-4]Транслитерация с других языков

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#229]
Разобраться с транслитерацией с любого языка, а не только с русского

Речь про заголовки страничек которые используются в качестве названия классов для пэйджобжектов

**Comment by savinovava** [comment]
As we discussed - this task was done. But it's needed to use emoji https://github.com/jdi-testing/jdn-ai/issues/185

**Comment by savinovava** [comment]
It is needed to update #216

**Comment by savinovava** [comment]
В качестве имени объекта берётся title name, сейчас поддерживается только транслитерация с кириллицы.
Возможно существует универсальная библиотека, которая всё транслитерирует (даже символы и иероглифы)
WOULD

**Comment by AlexeyGirin** [comment]
Либа найдена - Маша знает (но были проблемы со сборщиком, поэтому она не прикрутила)

**Comment by MariiaNebesnova** [comment]
вот она https://github.com/sindresorhus/transliterate
