### ISSUE TITLE
Undisplayed elements of context menu can not be selected

### ISSUE THREAD

**Issue by toshQA** [jdi-testing/jdn#234]
**Preconditions:**

- User installed JDN extension v.3.0.19 for Chrome Browser
- Docker was run

**Steps:**

1. Open site: https://jdi-testing.github.io/jdi-light/contacts.html
2. Open chrome dev tools on "JDN" tab
3. Click on "Identify" button
4. Wait for successful result
5. Click the right mouse button on any identified element 
6. Select "Change type"

**Expected result:** all elements of context menu can be selected

**Actual result:** only displayed elements of context menu can be selected

**PS:** there is an opened chrome dev tools in the bottom of screen on gif, that are not displayed
![Contact Form](https://user-images.githubusercontent.com/24373052/123915119-d3f8a700-d988-11eb-819e-177eba9b7d29.gif)

**Comment by DaryaGurtovenko** [comment]
Маша, проверь, пожалуйста, этот баг ещё воспроизводится в сборке 3.0.20

**Comment by toshQA** [comment]
Verified in v.3.0.20. Now there is a problem, that menu opens out of the bottom of the page, it will be fixed in redesign.
