### ISSUE TITLE
Автоматизация релиза

### ISSUE THREAD

**Issue by texonth** [jdi-testing/jdn#246]
https://github.com/jdi-testing/jdn/pull/245
 
Добавил гитхаб экшн который при пуше в мастер запускается, билдит проект, смотрит версию в пэкедже, и создает черновик релиза с прикрепленным файлом (подразумевается что пушить в мастер может только мерженый реквест).
Вписывает название релиза = вресии, гитхаб тег = версии и название файла = версии.
 
Этот драфт нужно аппрувнуть вручную (пока, если фича хорошо себя покажет можно отключить аппрув)
Так же можно будет поиграться с описанием релиза, названием.
 
Плюс добавил пакетик и нпм скрипт который одной командой обновляет версии в пэкедже и манифесте (правда для этого пока вынес манифест в корень и поменял путь в вебпаке, хз как в этом пакетике пути прописать, но мы все равно манифест трогаем только ради версии так что все равно где он лежит)
 
Так же этот пакетик может сам делать коммиты с обновлением версии, тоже добавим если хорошо себя покажет.

**Comment by AlexeyGirin** [comment]
Done
