### ISSUE TITLE
Создать генератор Angular элементов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#247]
Создать генератор тестовых страничек для Славы по примеру того, что сделал Семён для бутстрапа и HTML5
(Элементы должны быть обогащены дополнительной информацией для Славы).

Список элементов можно посмотреть тут: https://material.angular.io/components/categories
или тут - https://epam-my.sharepoint.com/:w:/r/personal/alexey_girin_epam_com/_layouts/15/Doc.aspx?sourcedoc=%7B0C5001CD-898A-489E-96FA-1F3DF92EA4E2%7D&file=table%20of%20elements.docx&action=default&mobileredirect=true

**Comment by MariiaNebesnova** [comment]
published `ng-mat-generator` branch

**Comment by AlexeyGirin** [comment]
Done.
