### ISSUE TITLE
Перекрасить квадраты

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#255]
Перекрасить прямоугольники покрытия в соответствии в дизайном Вероники

**Comment by mactopus** [comment]
Ссылка на дизайн https://www.figma.com/file/kZswCb9WEvRPX4gUtzeGhs/JDN-8-July?node-id=0%3A1
Доступ будет только по приглашению

**Comment by DaryaGurtovenko** [comment]
Перекрашено - ver. 3.0.29, функциональность проверена - ок
