### ISSUE TITLE
Перенос Robula+ на сторону сервера

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#259]

**Comment by aleksandrovskiys** [comment]
сервис доступен по адресу generate_xpath/ чтобы его использовать нужно будет пересобрать образ из registry.gitlab.com/vfuga/jdi-qasp-ml:latest/

На вход подается JSON с документом и списком xpath (например абсолютных). 
Пример входного JSON: [test_json.txt](https://github.com/jdi-testing/jdn/files/6840350/test_json.txt). 
В документе там страница angular с тестового сайта. Я получал документ так - JSON.stringify(document.documentElement.innerHTML). Можно передавать в документ и просто body.innerHTML, но тогда нужно учитывать, что и абсолютный xpath должен быть без //html/body. 

Возвращается JSON в котором переданные xpath будут ключами, а сгенерированные робулой - значениями.

**Comment by aleksandrovskiys** [comment]
Немного изменилась логика, на вход подаются id из jdn-hash, поэтому вместо поля xpaths в входном json будет поле ids с айдишниками.

**Comment by toshQA** [comment]
Request on generate_xpath/ on site: https://yandex.ru/ is failed without any error.
<img width="642" alt="image" src="https://user-images.githubusercontent.com/24373052/128333943-277719a3-6eef-4540-9b83-63dada403c40.png">

**Comment by MariiaNebesnova** [comment]
пададет с ошибкой `POST http://localhost:5000/generate_xpath net::ERR_CONNECTION_ABORTED`

**Comment by AlexeyGirin** [comment]
Ограничить глубину поиска таким образом что бы максимальное время поиска не превышало 5 секунд

**Comment by aleksandrovskiys** [comment]
добавил ограничение по количеству анализируемых робулой путей на 1500 шт. Это как раз примерно 5 секунд, для проверки нужно пересобрать контейнер из регистра.

**Comment by OlIva777** [comment]
проверила на https://www.spglobal.com/en/
тут пока замечания только по 1 типу xpath:
    @UI("//*[@aria-label='
										Who We Are
										
									']") public selector 1z689fAccMenuLink;
    @UI("//*[@aria-label='
										Careers
										
									']") public selector r9m598AccMenuLink;
    @UI("//*[@aria-label='
										Capabilities
										
									']") public selector z7dx7gAccMenuLink;
    @UI("//*[@aria-label='
										Research & Insights
										
									']") public selector sw4vfvAccMenuLink;
    @UI("//*[@aria-label='
										Events
										
									']") public selector 2zhus2AccMenuLink;


можно было бы сделать например так //li[contains(@aria-label, 'Research & Insights')]
Ну как минимум, предложенные варианты у меня даже не ищет в DOM

**Comment by OlIva777** [comment]
https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/contains

Все, что начинается с индекса выглядит странно. 
В идеале, индексы вообще избегать.
    @UI("//*[1]/*[@class='breadcrumb']") public Link link7;
    @UI("//*[2]/*[@class='breadcrumb']") public Link link38;
    @UI("//*[4]/*[contains(text(), 'Feedback')]") public Link link19;


Слишком сложный путь, можно например просто взять атрибут у гиперссылки
    @UI("/html/body/div[1]/footer/div/div[2]/ul/li[1]/a") public Link link42;
    @UI("/html/body/div[1]/footer/div/div[3]/ul/li[1]/a") public Link link44;

**Comment by aleksandrovskiys** [comment]
> проверила на https://www.spglobal.com/en/
> тут пока замечания только по 1 типу xpath:
> @ui("//*[@aria-label='
> Who We Are
> 

С плагина прилетает документ уже с табуляциями, @MariiaNebesnova это можно как-то пофиксить? Ну либо я просто могу обрезать пробельные символы при формировании, как лучше сделать?

![image](https://user-images.githubusercontent.com/4266410/129527999-866edf29-6cba-47cd-8e2b-1db760fc215c.png)

**Comment by MariiaNebesnova** [comment]
@aleksandrovskiys ты имеешь ввиду, что с плагина прилетают такие данные на /generate_xpath? насколько я помню робулу, я бы пробелы/неразрывные пробелы/табуляции обрезала где нибудь на этапе, когда робула этот икс пас собирает и проверяет.
я конечно же могу чистить икспасы на юае, но тогда получится неконсистентность между тем, что нагенерила (и проверила) робула и тем, что мы отдаем пользователю

**Comment by aleksandrovskiys** [comment]
@MariiaNebesnova сорри, я не посмотрел, что в элементе такие данные и есть, вместе с табуляциями и пробелами. Тогда да, конечно, буду править на генерации. А икспасс нормально отработает, если в элементе табы, а я их затру или заменю на пробелы? По сути текст же будет другой.

**Comment by MariiaNebesnova** [comment]
@aleksandrovskiys да, другой, но для пользователя - такой вариант понятнее. мы убираем символы которые не прочитать глазами

**Comment by aleksandrovskiys** [comment]
@OlIva777 пробельные символы пофиксил, последняя версия бэка - backend ver. 2021-08-16-08.37.30.

**Comment by OlIva777** [comment]
пробельные символы проверила  2021-08-16-08.37.30

**Comment by AlexeyGirin** [comment]
Done.
