### ISSUE TITLE
Needed content isn't attached in Report problem email

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#262]
The issue is when click 'Report problem' and do all needed steps the mail with correct text is created but its attachment is empty - there aren't needed files inside.
Is it even possible to add them? 

#205  

**Steps to reproduce:**
1 Open page which need to be tested 
2 Click 'Identify'
3 After prediction ended, click 'Report Problem' (at the bottom of tab on ver. dist_3_0_28.
4 Do all steps from instruction
5 Check the email

**Expected result**:
Email contains all needed files in attachment as screenshot, json and URL in single archive 

**Result**:
Attachment field is empty so we need some way to help user add files to mail

**Comment by Bryant-24** [comment]
In the first version, we decided to still give the screenshot and the json file separately (so as not to pull the JSZip library along with the extension).

**Comment by DaryaGurtovenko** [comment]
#269
