### ISSUE TITLE
Названия атрибутов классa начинаются с цифр

### ISSUE THREAD

**Issue by mikhnovich** [jdi-testing/jdn#264]
#242 
Страница:
https://www.amazon.com/international-sales-offers/b?ie=UTF8&node=15529609011&nocache=1626783607689

Пример:
```
@UI("#100 a096f341-announce") public Button 100a096f341Announce;
@UI("#100 3ec83634-announce") public Button 1003ec83634Announce;
```

**Comment by MariiaNebesnova** [comment]
это айдишник, в дереве выглядит так: 
![image](https://user-images.githubusercontent.com/82033805/126446128-4b9d7375-3cb7-4bae-b0bb-ed6d89cee095.png)

**Comment by AlexeyGirin** [comment]
В таких случаях добавлять префикс "name"
т.е. "100a096f341Announce" превращать в "name100a096f341Announce"

**Comment by OlIva777** [comment]
["2021-08-27-17.46.39"]  3.0.44

    @UI("//*[@id='100_dealView_15']") public TextField 100Dealview_15;
    @UI("//*[@id='100_dealView_18']") public TextField 100Dealview_18;

**Comment by OlIva777** [comment]
version 3.0.45 / backend 2021-07-30-11.15.44
    @UI("//*[@id='100 3990187d-announce']") public Button 1003990187dAnnounce;
    @UI("//*[@id='100 d3460f80-announce']") public Button 100d3460f80Announce;

**Comment by MariiaNebesnova** [comment]
fixed in ver 3.0.46

**Comment by OlIva777** [comment]
fixed: JDN version 3.0.49 / backend 2021-09-07-09.37.43

```
    @UI("//*[@data-gbdeal-actionrecord='{"actionType":"DEAL_CLICK","position":"13","widgetID":"100","dealID":"fe7831a2"}']/*[@class='a-row a-spacing-top-mini priceBlock']") public chip chipDiv15;
    @UI("//*[@data-gbdeal-actionrecord='{"actionType":"DEAL_CLICK","position":"5","widgetID":"100","dealID":"aa819108"}']/*[@class='a-row a-spacing-none a-size-mini']") public Button buttonDiv;
```
