### ISSUE TITLE
Генерируются одинаковые локаторы для разных элементов страницы

### ISSUE THREAD

**Issue by mikhnovich** [jdi-testing/jdn#265]
#242 
Необходимо исследовать данную проблему, потому что невозможно использовать одинаковый локатор для тестирования разных элементов страницы

Страница:
https://www.amazon.com/international-sales-offers/b?ie=UTF8&node=15529609011&nocache=1626783607689

Пример:
```
    @UI("#dealImage") public Link dealImage24;
    @UI("#dealImage") public Link dealImage25;
    @UI("#dealImage") public Link dealImage26;
    @UI("#dealImage") public Link dealImage27;
    @UI("#dealImage") public Link dealImage28;
    @UI("#dealImage") public Link dealImage29;
    @UI("#dealImage") public Link dealImage30;
    @UI("#dealImage") public Link dealImage31;
    @UI("#dealImage") public Link dealImage32;
```

**Comment by MariiaNebesnova** [comment]
скорее всего дело в нашем старом коде, не в робуле

**Comment by toshQA** [comment]
Works correctly. Verified in v. 3.0.34
