### ISSUE TITLE
Report problem - naming of content

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#275]
Needed new cool names for downloaded via 'Report problem' json file and screenshot. 
Now they're just 'json (N).txt' and 'screenshot (N).jpg' 
What we can do here:
- add 'JDN' to the start;
- add page name.

**Comment by mariia-tokarchuk** [comment]
JDN_report_problem_json (N).txt
JDN_report_problem_screenshot (N).jpg

**Comment by mariia-tokarchuk** [comment]
@DaryaGurtovenko Done

**Comment by mariia-tokarchuk** [comment]
JDN_report_problem_PageName_json (N).txt
JDN_report_problem_PageName_screenshot (N).jpg

+ как вариант, можно еще добавлять дату генерации файла
