### ISSUE TITLE
Протестировать отображение имени

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#281]
1. Показывать только изменённые имена
2. Показывать имя контрола всегда
3. Показывать тул тип при наведении

**Comment by mactopus** [comment]
1. Показывать всегда имена и дефолтные и измененные.
2. Несколько пользователей предложили сделать Name: Link без слова Change
3. Тултип выводить надо

**Comment by AlexeyGirin** [comment]
Ждём рисунок с тултипом

**Comment by mactopus** [comment]
![22](https://user-images.githubusercontent.com/8790565/130739267-cfd9fb4b-49ee-43d7-9c5e-cf1e0e457d23.png)

**Comment by AlexeyGirin** [comment]
1. Делаем тул тип со всеми данными (во много строчек - Name, Type, Locator, Threshold, что-то ещё?)
2. Меняем тип элемента на покрытии - на имя
3. Убираем Threshold с покрытия(?)

**Comment by AlexeyGirin** [comment]
Ждём скрины для имплементации

**Comment by mariia-tokarchuk** [comment]
![tooltip](https://user-images.githubusercontent.com/89466817/133451034-bdcda608-3d17-4c06-ba52-0f19cdfed903.png)

**Comment by AlexeyGirin** [comment]
Решили сделать тул тип пока без локатора (в тултипе оставить заглушку)
и создать одельную таску на добавление локатора

**Comment by marusyaganza** [comment]
Changes are in the version 3.0.54

**Comment by lisatatarinova** [comment]
протестировано, заведен баг #371
