### ISSUE TITLE
[9pt][US-5-2] Натренировать модель на распознавание MaterialUI элементов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#286]
Натренировать модель на распознавание HTML5 элементов на основе генератора размеченных страничек от @MariiaNebesnova  (Mariia Nebesnova)

[Related US](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2424884/Feature+list#US-5-2)

**Comment by AlexeyGirin** [comment]
Done.

**Comment by AlexeyGirin** [comment]
На сабсете в два раза больших данных

Будем надеятся что баги #344 и #340 будут пофикшены

**Comment by savinovava** [comment]
[10pt+] - подготовка
[5pt] - ML
[4pt] - QA

**Comment by AlexeyGirin** [comment]
1. Пофиксить баг в обучении.
Нужно пофиксить.
2. Вопросы к модели - нужно что-то менять. Фичи генерятся неверно. Отсюда разница между синтетикой и реальной жизнью. Вопросов много.

**Comment by AlexeyGirin** [comment]
Поисследовать проблему с кнопками на тестовой страничке - почему половина не распознаётся

**Comment by AlexeyGirin** [comment]
1. Посмотреть что с распознованием других контролов.
2. Добавить рул-бэйз предикшен для кнопок

**Comment by pulya-na-vullet** [comment]
Критичных багов не найдено, закрываю таску
