### ISSUE TITLE
[US-5-4] [Next release] Натренировать модель на распознавание Angular элементов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#287]
Натренировать модель на распознавание Angular элементов на основе генератора размеченных страничек от @MariiaNebesnova (Mariia Nebesnova)

- [x] https://github.com/jdi-testing/jdn-ai/issues/502

**Comment by ioffem** [comment]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/26673161/AngularJS+examples

**Comment by savinovava** [comment]
Duplicate https://github.com/jdi-testing/jdi-qasp-ml/issues/95
