### ISSUE TITLE
Xpath: только по названию элемента

### ISSUE THREAD

**Issue by OlIva777** [jdi-testing/jdn#291]
https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/contains

Может быть нестабильным, нужно уточнить, например аттрибут @name
    @UI("//select") public selector languageSelector;

["2021-08-16-08.37.30"]

**Comment by aleksandrovskiys** [comment]
Я думаю можно просто не учитывать такой вариант, когда в пути только тег элемента. Сейчас работает так потому что у тега просто выше приоритет генерации, если такой вариант пропустить, то следующий скорее всего будет с одним из приоритетных аттрибутов.

**Comment by AlexeyGirin** [comment]
Решение: Если локатор состоит из одного атрибута - то мы его игнорируем и ищем дальше

**Comment by aleksandrovskiys** [comment]
Исправлено. Версия - backend ver. 2021-08-19-08.42.28

**Comment by OlIva777** [comment]
**["2021-08-23-10.11.50"]** исправлено
    @UI("//*[@name='language']") public selector languageSelector;
