### ISSUE TITLE
Xpath: индексы в начале xpath

### ISSUE THREAD

**Issue by OlIva777** [jdi-testing/jdn#292]
https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/contains

Все, что начинается с индекса выглядит странно. 
В идеале, индексы вообще избегать.
    @UI("//*[1]/*[@class='breadcrumb']") public Link link7;
    @UI("//*[2]/*[@class='breadcrumb']") public Link link38;
    @UI("//*[4]/*[contains(text(), 'Feedback')]") public Link link19;

["2021-08-16-08.37.30"]

**Comment by OlIva777** [comment]
https://legal.thomsonreuters.com/en/products/practical-law

    @UI("//*[24][@async='']") public UIElement uielementScript;
    @UI("//*[23][@type='text/javascript']") public UIElement uielementScript89;
    @UI("//*[20][@type='text/javascript']") public UIElement uielementScript90;

**Comment by OlIva777** [comment]
https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all

    @UI("//*[1]/div[@class='m-nav-panel-link m-nav-txt-small'][5]") public Button buttonDiv67;
    @UI("//*[8]/*[@target='_blank']") public Link link85;
    @UI("//*[3]/*[contains(text(), 'Bahasa Indonesia')]") public Link link141;
    @UI("//*[16]/*[contains(text(), '中文 (简体)')]") public Link link161;
    @UI("//*[17]/*[contains(text(), '中文 (繁體)')]") public Link link162;

**Comment by OlIva777** [comment]
https://investors.danaher.com/quarterly-earnings

    @UI("//*[3]/*/*/a[contains(text(), 'Form 10-Q')]") public Link link123;
    @UI("//*[3]/*/*[contains(text(), 'Form 10-Q')][@target='_blank']") public Link link127;

**Comment by AlexeyGirin** [comment]
Решение: Убираем индексы (но так что бы можно было легко включить их обратно в коде) и увеличиваем время поиска до 10 секунд

**Comment by aleksandrovskiys** [comment]
Генерация по индексам отключена в версии backend ver. 2021-08-19-08.42.28.

**Comment by OlIva777** [comment]
**["2021-08-23-10.11.50"]** проверено
https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/contains
https://legal.thomsonreuters.com/en/products/practical-law
https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all
https://investors.danaher.com/quarterly-earnings
