### ISSUE TITLE
Xpath: индексы в конце - нестабильный локатор

### ISSUE THREAD

**Issue by OlIva777** [jdi-testing/jdn#293]
https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/contains

    @UI("//*[@class='footer-legal']/*[3]") public Link linkLi;
    @UI("//*[@class='footer-legal']/*[2]") public Link linkLi31;

["2021-08-16-08.37.30"]

**Comment by OlIva777** [comment]
https://legal.thomsonreuters.com/en/products/practical-law

    @UI("//script[43]") public UIElement uielementScript101;
    @UI("//script[46]") public UIElement uielementScript102;
    @UI("//script[47]") public UIElement uielementScript103;

**Comment by AlexeyGirin** [comment]
Решение: Убираем индексы (но так что бы можно было легко включить их обратно в коде) и увеличиваем время поиска до 10 секунд

**Comment by aleksandrovskiys** [comment]
Генерация по индексам отключена в версии backend ver. 2021-08-19-08.42.28.

**Comment by OlIva777** [comment]
["2021-08-23-10.11.50"]
функция "вкл/выкл индексы в конце" работает
