### ISSUE TITLE
Xpath: индексы в середине - нестабильный локатор

### ISSUE THREAD

**Issue by OlIva777** [jdi-testing/jdn#294]
https://investors.danaher.com/quarterly-earnings

    @UI("//*[@class='wd_category_items wd_category_items_16']/*[1]/*/*[5]") public Link link13;
    @UI("//*[@class='wd_category_items wd_category_items_3']/*[2]/*/*[5]") public Link link20;
    @UI("//*[@class='wd_category_items wd_category_items_4']/*[2]/*/*[5]") public Link link21;
    @UI("//*[@class='wd_category_items wd_category_items_14']/*[2]/*/*[5]") public Link link22;
    @UI("//*[@class='wd_category_items wd_category_items_3']/*[1]/*/*[5]") public Link link23;
    @UI("//*[@class='wd_category_items wd_category_items_3']/*[4]/*/*[5]") public Link link24;
    @UI("//*[@class='wd_category_items wd_category_items_4']/*[1]/*/*[5]") public Link link25;
    @UI("//*[@class='wd_category_items wd_category_items_14']/*[3]/*/*[5]") public Link link26;
    @UI("//*[@class='wd_category_items wd_category_items_14']/*[4]/*/*[5]") public Link link27;
    @UI("//*[@class='wd_category_items wd_category_items_1']/*[3]/*/*[contains(text(), 'Non-GAAP Recs')]") public Link link28;
    @UI("//*[@class='wd_category_items wd_category_items_12']/*[1]/*/*[contains(text(), 'Non-GAAP Recs')]") public Link link29;
    @UI("//*[@class='wd_category_items wd_category_items_18']/*[4]/*/*/*[contains(text(), 'Non-GAAP Recs')]") public Link link30;
    @UI("//*[@class='wd_category_items wd_category_items_12']/*[2]/*/*[contains(text(), 'Non-GAAP Recs')]") public Link link31;
    @UI("//*[@class='wd_category_items wd_category_items_12']/*[3]/*/*[contains(text(), 'Non-GAAP Recs')]") public Link link32;
    @UI("//*[@class='wd_category_items wd_category_items_1']/*[2]/*/*[contains(text(), 'Non-GAAP Recs')]") public Link link33;

["2021-08-16-08.37.30"]

**Comment by AlexeyGirin** [comment]
Решение: Убираем индексы (но так что бы можно было легко включить их обратно в коде) и увеличиваем время поиска до 10 секунд

**Comment by aleksandrovskiys** [comment]
Генерация по индексам отключена в версии backend ver. 2021-08-19-08.42.28.

**Comment by OlIva777** [comment]
["2021-08-23-10.11.50"]
функция "вкл/выкл индексы в конце" работает
