### ISSUE TITLE
Xpath: лишние слэш-символы /*/*/*

### ISSUE THREAD

**Issue by OlIva777** [jdi-testing/jdn#295]
https://investors.danaher.com/quarterly-earnings

    @UI("//*[@class='wd_category_items wd_category_items_14']/*[1]/*/*[contains(text(), 'Form 10-Q')]") public Link link128;
    @UI("//*[@class='wd_category_items wd_category_items_14']/*[2]/*/*[contains(text(), 'Form 10-Q')]") public Link link129;
    @UI("//*[@class='wd_category_items wd_category_items_14']/*[3]/*/*[contains(text(), 'Form 10-Q')]") public Link link130;
    @UI("//*[@class='wd_category_items wd_category_items_18']/*[1]/*/*/*[contains(text(), 'Form 10-Q')]") public Link link131;
    @UI("//*[@class='wd_category_items wd_category_items_20']/*[2]/*/*/*[contains(text(), 'Form 10-Q')]") public Link link132;
    @UI("//*[@class='wd_category_items wd_category_items_18']/*[2]/*/*/*[contains(text(), 'Form 10-Q')]") public Link link133;
    @UI("//*[@class='wd_category_items wd_category_items_20']/*[1]/*/*/*[contains(text(), 'Form 10-Q')]") public Link link134;
    @UI("//*[@class='wd_category_items wd_category_items_12']/*[3]/*/*[7]") public Link link135;
    @UI("//*[@class='wd_category_items wd_category_items_1']/*[1]/*/*[contains(text(), 'Form 10-Q')]") public Link link136;
    @UI("//*[@class='wd_category_items wd_category_items_1']/*[2]/*/*[contains(text(), 'Form 10-Q')]") public Link link137;
    @UI("//*[@class='wd_category_items wd_category_items_1']/*[3]/*/*[contains(text(), 'Form 10-Q')]") public Link link138;
    @UI("//*[@class='wd_category_items wd_category_items_2']/*[1]/*/*[contains(text(), 'Form 10-Q')]") public Link link139;
    @UI("//*[@class='wd_category_items wd_category_items_2']/*[2]/*/*[contains(text(), 'Form 10-Q')]") public Link link140;
    @UI("//*[@class='wd_category_items wd_category_items_16']/*/*/*/*[contains(text(), 'Form 10-K')]") public Link link144;

можно убрать лишние символы 
    @UI("//*[@class='wd_category_items wd_category_items_18']/*/*/*/*[contains(text(), 'Form 10-K')]") public Link link145;
и заменить на 
    @UI("//*[@class='wd_category_items wd_category_items_18']//*[contains(text(), 'Form 10-K')]") public Link link145;

["2021-08-16-08.37.30"]

**Comment by aleksandrovskiys** [comment]
Если их убирать, то есть вероятность того, что путь перестает быть уникальным:
![image](https://user-images.githubusercontent.com/4266410/129883803-d50d30b3-275b-439a-bf0c-360f6c39b2fc.png)
![image](https://user-images.githubusercontent.com/4266410/129883774-2e2f9ee9-5e46-48cd-8815-0e69c1e6371e.png)

**Comment by aleksandrovskiys** [comment]
исправил для путей, где это не ведет к потере уникальности
backend ver. 2021-08-18-10.48.42

**Comment by AlexeyGirin** [comment]
Ждём версии которая позволит выставлять максимальное время поиска

**Comment by OlIva777** [comment]
**["2021-08-23-10.11.50"]** проверено
https://investors.danaher.com/quarterly-earnings
    @UI("/html/body/div[3]/div/div/article/div/div/div/div[2]/div/div/div[7]/div[2]/div[2]/p/a[4]") public Link link140;
    @UI("//*[@class='wd_category_items wd_category_items_16']//*[contains(text(), 'Form 10-K')]") public Link link144;
