### ISSUE TITLE
Перепридумать визуализацию ожидания генерации локаторов - ИМПЛЕМЕНТАЦИЯ

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#296]
В данный момент - процесс генерации локаторов начинается после того как контролы распознались моделью и продолжается асинхронно.
Есть подозрение, что у нас не получится ускорить этот процесс что бы он занимал разумное (5-15 секунд) время. Это обречено занимать минуты.
Необходимо подумать как сделать так, что бы процесс генерации был виден пользователю и (возможно) как-то мог влиять на него (например - менять приоритет или порядок генерации того или иного контрола)

**Comment by mactopus** [comment]
<img width="757" alt="Screenshot 2021-08-19 at 17 15 28" src="https://user-images.githubusercontent.com/8790565/130085031-b4098463-0249-4718-a165-4c9e03cf5123.png">
как вариант сделать прелоадер в виде полоски, которая будет двигаться от левого края к правому

**Comment by mactopus** [comment]
<img width="735" alt="Screenshot 2021-08-24 at 08 39 05" src="https://user-images.githubusercontent.com/8790565/130561957-b87fba47-b494-4afb-958f-2d1b8858b266.png">

**Comment by AlexeyGirin** [comment]
1. Нарисовать вариант локатора который ещё не просчитан (вставлять полный xPath)
2. Нарисовать вариант с меню для каждого элемента позволяющего манипулировать генерацией (с пунктами - Skip Locator Generation)
3. Нарисовать отображение трёх состояний генерации каждого локатора - Сгенерён, генерится и ожидает генерации

**Comment by AlexeyGirin** [comment]
Визуальная часть есть, Ждём тестирования

**Comment by AlexeyGirin** [comment]
Тестирование завершено - дизайн выложен https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN?node-id=0%3A1
(ветка с жёлтыми скринами)

**Comment by AlexeyGirin** [comment]
1. Владку инвизибл оставляем но не реализует (она для невидимых элементов у которых есть координаты, но линейные размеры равны нулю)

**Comment by AlexeyGirin** [comment]
Декомпозирована на мелкие задачи. Закрываем
