### ISSUE TITLE
[US-2-2] Придумать дизайн для опций генерации локаторов - ИМПЛЕМЕНТАЦИЯ

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#301]
Придумать дизайн который позволит выставить некоторые параметры для генератора локаторов.
Следующий список параметров мы уже знаем что будет:
1. Allow indexes at the beginning - (unchecked by default)
2. Allow indexes at the middle - (unchecked by default)
3. Allow indexes at the end - (checked by default)
4. Limit generation time to [time picker here] - (default values for timepicker - 10 sec, checked by default)

[Related US-2-2](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2424884/Feature+list#US-2-2)

**Comment by mactopus** [comment]
<img width="681" alt="Screenshot 2021-08-24 at 08 28 34" src="https://user-images.githubusercontent.com/8790565/130560873-68607121-d5c7-470c-a5fa-3fa145f8572a.png">

**Comment by mactopus** [comment]
<img width="594" alt="Screenshot 2021-08-24 at 08 30 01" src="https://user-images.githubusercontent.com/8790565/130561023-ff60ed34-ea3d-4a0c-980a-151b6a8882e0.png">

**Comment by AlexeyGirin** [comment]
Нарисовать вариант с тайм пикером

**Comment by mactopus** [comment]
![23](https://user-images.githubusercontent.com/8790565/130740103-628141b3-f2e4-493a-9914-a55b31ebffe3.png)

**Comment by mactopus** [comment]
Нужны тексты в подсказки (вопросики)

**Comment by AlexeyGirin** [comment]
@mariia-tokarchuk 
1. Do not let generate locators with indexes (such as @ui("//**[1]**/[@Class='breadcrumb']")) at the beginning
2. Do not let generate locators with indexes (such as @UI("//*[@class='items_16']/***[1]**/*/*")) in the middle
3. 1. Do not let generate locators with indexes (such as @UI("//*[@class='legal']/***[3]**")) at the end

**Comment by mariia-tokarchuk** [comment]
![settings](https://user-images.githubusercontent.com/89466817/134012763-3fe27ebb-cd64-4afd-b379-ef9c97095b38.png)

**Comment by AlexeyGirin** [comment]
Где будем хранить настройки на время сессии? на всё время?
Нужна консультация Маши
