### ISSUE TITLE
Update example for Maksim

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#304]
Максим попытался раскочегарить пример https://github.com/jdi-examples/jdi-dark-report-portal-demo для старта своего проекта, но он не работает
Необходимо починить что бы он работал

**Comment by n-ton4** [comment]
<repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>bintray-epam-reportportal</id>
            <name>bintray</name>
            <url>http://dl.bintray.com/epam/reportportal</url>
        </repository>
    </repositories>

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by AlexeyGirin** [comment]
Done (but w/out check)
