### ISSUE TITLE
Проверка сгенерированных xpath локаторов

### ISSUE THREAD

**Issue by OlIva777** [jdi-testing/jdn#308]
Проверить сгенерированные xpath локаторы на разных сайтах и разных версиях JDN

**Comment by OlIva777** [comment]
**["2021-08-16-08.37.30"]**

- https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/contains
- https://www.spglobal.com/en/
- https://legal.thomsonreuters.com/en/products/practical-law
- https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all
- https://investors.danaher.com/quarterly-earnings

**Comment by OlIva777** [comment]
**["2021-08-23-10.11.50"]**

- https://outlook.office.com/mail/inbox
- https://www.dentsplysirona.com/ru-ru
- https://www.sj.se/en/home.html#/tidtabell/Stockholm%2520Central/G%25C3%25B6teborg%2520C/enkel/avgang/20210825-1832/avgang/20210825-1900/SU-20--false///0// --->step Timetable

Длинные названия локаторов, абсолютный путь, индексы

**Comment by OlIva777** [comment]
version 3.0.46 backend 2021-08-27-17.46.39
https://www.lenmosty.ru/timetable
https://hd.kinopoisk.ru/watchlist
https://www.wildberries.ru/catalog/bytovaya-tehnika/krupnaya-bytovaya-tehnika?sort=popular&page=1

**Comment by OlIva777** [comment]
version 3.0.46 / backend 2021-09-05-13.54.50

- https://www.bbc.com/worklife
- https://www.netflix.com/ru-en/
- https://www.salesforce.com/

**Comment by toshQA** [comment]
extension v. 3.0.46 / backend backend 2021-08-27-17.46.39

https://web-staging.trading.com/ https://www.admitad.com/
https://lenta.com/
https://stackoverflow.com/
https://jdi.epam.com/
https://about.gitlab.com/

**Comment by AlexeyGirin** [comment]
Decided to close
