### ISSUE TITLE
[1.5pt][US-1-1]При закрытии плагина убирать со страницы добавленные плагином элементы

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn#313]
При закрытии всей консоли разработчика
- Элементы подсветки
- Report a problem
- контекстное меню
- settings
- edit name
- download confirmation
+ чистить подписки на события

**Comment by savinovava** [comment]
[1pt]-front
[0.5pt] - QA

**Comment by marusyaganza** [comment]
Fixed in version 3.0.71

**Comment by pulya-na-vullet** [comment]
Баг воспроизводится на странице Confluence:
JDN v 3.0.75
Back-end v 2021-11-01-06.14.14
![image](https://user-images.githubusercontent.com/61897393/142572950-7e41a079-b938-4f13-a3a0-b12ab9313005.png)

**Comment by MariiaNebesnova** [comment]
на версии 3.0.94 не воспроизводится

**Comment by pulya-na-vullet** [comment]
Ретест бага произведен
JDN v 3.0.99
Back-end v 2021-11-26-14.32.52
Баг не воспроизводится.
