### ISSUE TITLE
Имплементация отзывчивого дизайна

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn#314]
В данным момент дизайн реализован для мин ширины окна 694px.
По существующим макетам необходимо имплементировать верстку для ширины 
- 320px https://www.figma.com/file/PyIi7jiriB4nAZi9kg7SNd/JDN?node-id=201%3A1462
- 52px https://www.figma.com/file/PyIi7jiriB4nAZi9kg7SNd/JDN?node-id=201%3A1430

**Comment by AlexeyGirin** [comment]
Не актуальна
