### ISSUE TITLE
Уменьшить линейные размеры элементов дизайна плагина

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#317]
Текущая имлементация дизайна слишком велика и занимает половину экрана.
Нужно привести линейные размеры элементов и шрифтов в соотвествие с панелью дев консоли

**Comment by mariia-tokarchuk** [comment]
![Plugin - max width](https://user-images.githubusercontent.com/89466817/131686189-63d6a872-0921-456d-80fe-32b05fc8dd14.png)
![Plugin - width 320](https://user-images.githubusercontent.com/89466817/131686197-04b2ffca-5339-4828-9a4b-edeec872f902.png)
![Plugin - width 500](https://user-images.githubusercontent.com/89466817/131686200-01e3ad5f-f221-4378-9a1a-73657d3d03fa.png)
![Plugin-horisontal](https://user-images.githubusercontent.com/89466817/131686202-ed5ed0ef-b13c-4d9c-9e04-7a7c9d9feb2c.png)

Показала дизайн с учетом разной ширины плагина, а также горизонтальной версии

**Comment by AlexeyGirin** [comment]
Завести баги на приведение существующего дизайна к референсному из скриншотов (обращать внимание на линейные размеры элементов)

**Comment by AlexeyGirin** [comment]
Done.
