### ISSUE TITLE
Xpath: локатор по названию элемента и *

### ISSUE THREAD

**Issue by OlIva777** [jdi-testing/jdn#318]
version 3.0.46/backend 2021-08-27-17.46.39

https://www.lenmosty.ru/timetable
`  @UI("//p/*") public Link link20;`

будет лучше например такой `//p/a`

**Comment by aleksandrovskiys** [comment]
Исправлено - backend ver. 2021-09-05-13.54.50

**Comment by OlIva777** [comment]
Проверено
version 3.0.46 / backend 2021-09-05-13.54.50
`    @UI("//p/a") public Link link18;
`
