### ISSUE TITLE
Update the current design - reduction of elements in accordance with the mock-up

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#319]
The task is a direct continuation of the task #317.
The issue is existing implementation has too large elements and space between them so in general, everything is not very convenient. Need to **redo the plugin** in accordance with the mock-ups.
Design can be found [here](https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN?node-id=0%3A1)

**Comment by Dashnik** [comment]
Следующие изменения необходимо внести в верстку(согласовано с Марией Т.):
1) Уменьшить хедер по высоте.
2) Слово JDN должно быть в строке с номером версии.
3) Адаптировать дизайн при изменение ширины плагина.
4) Настройки Xpath как в макете.
5) В дизайне при горизонтальном отображении контент внутри плагина делится на 2 колонки.
6) Изменить размер кнопок.
7) Убрать полосы над и под 'Perseption threshold' и проверить расстояние к кнопкам и xpath settings.

**Comment by AlexeyGirin** [comment]
Ждём одобрения пулл реквеста

**Comment by lisatatarinova** [comment]
@Dashanchik @AlexeyGirin 

1. Уменьшить хедер по высоте. - **PASSED**.
2. Слово JDN должно быть в строке с номером версии. - **PASSED**.
3. Адаптировать дизайн(Хедер) при изменение ширины плагина. - **_Partly passed_**.
**Issue:**
версии JDN и бека совсем пропадают при ширине страницы от 1524 до 1625
![image](https://user-images.githubusercontent.com/34272388/135107417-2cb2ce26-2260-4fcb-88d8-a311d24529f7.png)
4. Изменить размер кнопок. - **PASSED**.
5. Убрать полосы над и под 'Perseption threshold' и проверить расстояние к кнопкам и xpath settings. - **PASSED**
