### ISSUE TITLE
Right click doesn't call context menu but duplicate left click

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#321]
On ver.3.0.46, MacOS, Mariia run into the issue - she tried to call the context menu of element via RMB but instead only states of elements were changed - just like if she clicked LMB. 
There weren't any messages in plugin's console in any tabs but she had an error in Chrome's extension tab:
<img width="1440" alt="ChrExt 46" src="https://user-images.githubusercontent.com/80756170/132303903-83229b11-7f06-4c0e-81c5-beb15d623e39.png">
Anton tried to reproduce the issue but had correct work of plugin - context menu was opened after RBM click.
I have Windows OS, and I don't have such issue.

**Comment by mariia-tokarchuk** [comment]
проблема решена. в браузере был включен режим разработчика, поэтому плагин не распознавал клик ПКМ.
