### ISSUE TITLE
[2.5pt][US-6-2] Need to add the confirmation of clearing after some changes (Clear all confirmation)

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#323]
Need to add confirmation if an user does some changes on marked up page/in locators list and click 'Clear' button after this.

To discuss:
1. Will we show the confirmation after changes or in any case?
2. Will we show the confirmation in case of closing Dev console?
3. Implementation: the same modal window as Chrome shows or some fancy design thing?

**Comment by AlexeyGirin** [comment]
Обсудили - Маша подумает над дизайном

**Comment by mariia-tokarchuk** [comment]
1. We will show the confirmation of clearing in any case.
2. We will show the confirmation in case of closing Dev console
3. Implementation: modal windows will be as the plugin's design style

Design files attached

![clear all](https://user-images.githubusercontent.com/89466817/137871809-a5dbabc0-dc11-4494-a3a9-d77dc1b0486e.png)

![close dev console](https://user-images.githubusercontent.com/89466817/137871816-c7fc7144-647e-45d2-9dbb-f04188e0c04d.png)

**Comment by MariiaNebesnova** [comment]
после #369

**Comment by savinovava** [comment]
[2pt] -front
[0.5pt] -QA

**Comment by MariiaNebesnova** [comment]
делаем только Clear All

**Comment by ioffem** [comment]
is not actual anymore
