### ISSUE TITLE
Need to make 'Name changed' popup disappear in 2 secs

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#324]
The idea is Name changed' popup which is showed after changing of name via context menu disappear in couple of seconds. Currently it is snowed forever.

**Preconditions:**
1 JDN plugin is installed (v.3.0.4)
2 Developer console is open and JDN is chosen
3 Some page is opened (never do it without opened page)

**Steps to reproduce:**
1 Click 'Identify' button
As result some objects are marked on page 
2 Call context menu of any element by clicking on it RMB
3 Chose 'Change name' item in context menu list 
4 Click 'Save' button to confirm the change

**Expected result:**
Popup appears for 2 secs and disappears after

**Actual result:**
Popup appears and never leaves.
After calling the menu in second and subsequent times another popup windows are opened and stay there forever

**Comment by marusyaganza** [comment]
fixed in version 3.0.50
