### ISSUE TITLE
Переключить фронт на новую модель

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#325]
Связаться с Семёном (@aleksandrovskiys ) и переключить фронт с ручки старой модели на ручку новой

**Comment by Dashnik** [comment]
Старый эндпоинт(http:localhost:5000/predict) был заменен на новый (http:localhost:5000/mui-predict).
release:
https://github.com/jdi-testing/jdn/releases/tag/3.0.48

**Comment by Dashnik** [comment]
Перед работой убедитесь, что версия бекэнда от 2021-09-07-09.37.43 или позднее. Иначе могут возникнуть конфликты.
Для наглядности: 
![image](https://user-images.githubusercontent.com/35660327/132526315-fa373079-c7c8-42fb-aa3a-81bb031a8fb0.png)
