### ISSUE TITLE
Придумать элементы управления генерацией - ИМПЛЕМЕНТАЦИЯ

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#327]
Сейчас генерация локаторов запускается сразу после распознования контролов моделью и идет асинхронно пока не закончится. Это занимае существенное время даже если распараллелить и ограничить время генерации одного локатора. 
Поэтому, нужно придумать механику управления генерацией на подобии того как это сделано в Менеджере закачек
(разумеется с адаптацией, а не один в один :-) )
![image](https://user-images.githubusercontent.com/26869421/132510767-6dc4c6a8-25a3-4476-872b-2dc33cc7badb.png)

**Comment by AlexeyGirin** [comment]
1. Добавить визуализацию процесса генерации на неактивный таб Waiting
2. Подумать как мы будем применять сеттинги
Оставляем глобальную кнопку? Добавляюем локальные для каждой строки? А как это визуализировать?

**Comment by AlexeyGirin** [comment]
1. Переключаемся на второй вариант
2. Ручку для изменения порядка строе - оставляем только в Waiting for generation

**Comment by mariia-tokarchuk** [comment]
ссылка на фигму - https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN?node-id=0%3A1

![1](https://user-images.githubusercontent.com/89466817/134634967-09b4f6a6-0695-4201-a924-dd0a511fbd65.png)
![2](https://user-images.githubusercontent.com/89466817/134634974-01244da9-0345-40fe-b256-8fbd3f7fe66e.png)

**Comment by AlexeyGirin** [comment]
Done. (Decomposed to another issues)
