### ISSUE TITLE
[US-7-3]Добавить валидацию имени

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#330]
В данный момент - валидация имени контрола которые отредактировал пользователь - не осуществляется.
У нас есть две опции:
1. Если найдём библиотечку которая сможет это делать - нужно её прикрутить (по сути - валидатор должен проверять что имя контрола - это валидное имя переменной в жаве)
2. Если ничего не найдём - стоит оставить валидацию на совести пользователя и использовать принцип garbage in - garbage out

**Comment by savinovava** [comment]
@MariiaNebesnova to discuss

**Comment by AlexeyGirin** [comment]
Done.
