### ISSUE TITLE
Перенести инфу по API в документацию в репозитории

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#334]
Сейчас иформация по API из задачи #316 находится только там и может потеряться.
Нужно перенести её хотя бы в readme репозитория бэкэнда

**Comment by aleksandrovskiys** [comment]
перенес в ветку develop

**Comment by AlexeyGirin** [comment]
https://gitlab.com/vfuga/jdi-qasp-ml
