### ISSUE TITLE
Not all elements are identified on react material UI sites

### ISSUE THREAD

**Issue by toshQA** [jdi-testing/jdn#336]
**Preconditions:**

- user installed JDN extension v.3.0.50
- backend 2021-09-07-09.37.43

**Steps:**

1. Open site "https://mui.com/components/buttons/"
2. Open chrome dev tools
3. Click on tab of JDN extension
4. Click on "Identify" button
5. Wait for finishing the process
6. Scroll page down

**Expected result:** all elements are identified

**Actual result:** not all elements are identified

**Comment by AlexeyGirin** [comment]
Ждём нового дата сайнтиста

**Comment by savinovava** [comment]
This task was specified later. Website is added to https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/18251877/Examples+of+webpages
