### ISSUE TITLE
[US-5-2] Проверить версию с моделью только для Material UI

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#337]
Последнияя версия бэкэнда (50 и выше) содержит модель на распознование (react) Material UI контролов.
Нужно проверить, что распознование работает хорошо на разных сайтах использующих Material UI element library (реактовский т.к. бывают ещё не реактовские).
Нужно найти эти сайты и посмотреть - все ли контролы распознаяются. Если что-то где-то не распознаётся - создавать баги на Нину - будем пытаться понять почему так

**Comment by AlexeyGirin** [comment]
Приостанавливаем до появления дата сайнтиста

**Comment by savinovava** [comment]
Задача будет возвращена в работу после пересоздания Material UI jdn#286
