### ISSUE TITLE
Отрисовать кебаб меню для хеадера

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#341]
Сейчас, при вертикальной расположении лэйаута плагина есть вариант когда пользователь уменьшает широту плагина настолько, что кнопки перестают помещаться.
Необходимо прятать их в кебаб меню

**Comment by mariia-tokarchuk** [comment]
![kebab menu](https://user-images.githubusercontent.com/89466817/134659892-90094665-5291-41cd-8d76-90c0117489ae.png)
