### ISSUE TITLE
[5pt][NR-3] Переключить фронт на новый бэк

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#342]
Изменить бэкэнд. Переключиться на web socket с flask (который сейчас)
Это даёт преимущество установленного соединения через который можно общаться в обе стороны (и посылать всякие пуши и вот это всё)

И FastAPI на который тоже можно перейти и в итоге фронтенд станет проще

Сколько это займёт? Если человек работал - то быстро - 1 неделя

Это умнее чем с клиента пинговать сервер

RabbitMQ - туда соваться не надо. В питоне это и так реализуется одной библиотекой.

**Comment by AlexeyGirin** [comment]
Решили попробовать, но после того как закончим переделывать новый UI

**Comment by MariiaNebesnova** [comment]
4pt - fe

**Comment by DaryaGurtovenko** [comment]
0.5 pt - qa

**Comment by MariiaNebesnova** [comment]
3.1.112

**Comment by ioffem** [comment]
JDN v 3.1.113
Back-end v 2022-01-21-15.18.28
Chrome

Performed regression.
Seems to be done.

QA - 0.5pt
