### ISSUE TITLE
[2.5pt][US-5-2] Разное распознавание компонентов одной и той же страницы локально и в сети

### ISSUE THREAD

**Issue by lisatatarinova** [jdi-testing/jdn#344]
JDN version 3.0.50
backend 2021-09-07-09.37.43
resources downloaded from https://material-ui.com/store/items/devias-kit/, runs locally via node.js

1. Открыть web-site https://material-kit-react.devias.io/app/customers
2. Открыть JDN
2. Установить Perception treshold: 0
3. Нажать Identify
**Actual result:** 45 components predicted
![image](https://user-images.githubusercontent.com/34272388/134498742-93a32585-02b3-4055-891c-1a8c6b5ac916.png)

4. Запустить приложение локально
5. Открыть JDN
6. Установить Perception treshold: 0
7. Нажать Identify
**Actual result:** 64 components predicted
![image](https://user-images.githubusercontent.com/34272388/134499842-bb639d77-495d-4cc5-bc9c-b514131840af.png)

**Expected result:** результат работы идентификатора и генератора компонентов одинаковый для локально запущенных web-приложений и web-приложений в сети

**Note:** Разница между Identify локально/в сети

- Локально нашел Buttons навигации
<Box sx={{ p: 2 }}>
        <List>
          {items.map((item) => (
            <NavItem
              href={item.href}
              key={item.title}
              title={item.title}
              icon={item.icon}
            />
          ))}
        </List>
- Локально определил чекбоксы как чекбоксы + paper/slider 
![image](https://user-images.githubusercontent.com/34272388/134501929-60712ecf-4fc3-46f2-b16e-ae5d530f5627.png)
- Локально нашел popper в таблице
![image](https://user-images.githubusercontent.com/34272388/134502241-0b139db3-eb74-4e1d-9bdd-6a33dd1c74da.png)
- Локально на месте TablePagination нашел контейнер
![image](https://user-images.githubusercontent.com/34272388/134502546-79ba213d-183b-4841-8f87-05f4f42dd1ac.png)
- Локально нашел Button 
![image](https://user-images.githubusercontent.com/34272388/134502615-2387a885-2a1a-4a7f-8f37-ba9796bba8f8.png)
<Button
            color="primary"
            component="a"
            href="https://react-material-kit.devias.io"
            variant="contained"
          >
            See PRO version
          </Button>
[Related US-5-2](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12877868/US-5-2+Recognition+of+elements+from+library+Material+UI)

**Comment by savinovava** [comment]
Оценка аналогично #340

**Comment by savinovava** [comment]
@lisatatarinova необходимо обновить актуальность

**Comment by lisatatarinova** [comment]
сайт больше недоступен, баг неактуален
