### ISSUE TITLE
[1pt] Часть компонентов "падает" в "unreachable due to DOM updates"

### ISSUE THREAD

**Issue by lisatatarinova** [jdi-testing/jdn#347]
JDN version 3.0.50
backend 2021-09-07-09.37.43

1. Открыть web-site https://material-kit-react.devias.io/app/customers
2. Открыть JDN
3. Установить Perception treshold: 0
4. Нажать Identify
**Actual result:** 45 components predicted
5. Подождать окончания генерации (~ 3 сек)
**Actual result:** появилось сообщение "21 controls are unreachable due to DOM updates", 24 components available for generation
**Expected result:** все идентифицированные контролы доступны для генерации
6. Сгенерировать файл
**Actual result:** следующие контролы не сгенерировались:
```
@UI("//*[@class='MuiAvatar-root MuiAvatar-circular css-1fqoqdp-MuiAvatar-root']/img") (x10)
@UI("//*[@class='PrivateSwitchBase-input css-mraihx") (x10)
```
Картинка для наглядности. компоненты с зеленой галкой - успех, с красным крестом - unreachable due to DOM updates
![image](https://user-images.githubusercontent.com/34272388/134631616-4b1de85e-be88-4214-8a30-efbe925bcf98.png)
**Expected result:** если элементы страницы не были изменены в процессе идентификации/генерации локаторов, "unreachable due to DOM updates" не возникает

**Comment by aleksandrovskiys** [comment]
Исправлено в Back-end v 2021-11-01-06.14.14

**Comment by savinovava** [comment]
@lisatatarinova оцени, пожалуйста

**Comment by lisatatarinova** [comment]
текущий таск неактуален, создан новый
https://github.com/jdi-testing/jdn/issues/379
