### ISSUE TITLE
[0.5pt][US-6-5] Locator generation status

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn#352]
Decomposition of #327 

Implement locator generation status bar in the bottom of the locators list

[Related US-6-5](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2424884/Feature+list#US-6-5)

https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN?node-id=1144%3A97713

**Comment by pulya-na-vullet** [comment]
Waiting  for generation работает корректно. Элементы управления соответствуют Figma.
Статус генерации работает корректно. 
Не все статусы в Progress line работают корректно:
https://github.com/jdi-testing/jdn/issues/388
