### ISSUE TITLE
[0.5pt] [-] Generation-in-progress highlight

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn#353]
Decomposition of #327 

According to design, for tasks in status STARTED, make a highlight with dashed border

[Related US-6-2](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2424884/Feature+list#US-6-2)

**Comment by MariiaNebesnova** [comment]
3.0.66

**Comment by lisatatarinova** [comment]
tested, ok
