### ISSUE TITLE
[US-6-1] Sticky locator groups header

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn#354]
Decomposition of #327 

UC here: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12910649/US-6-1+See+the+generated+elements#UC-6-1-2-Sticky-locator%E2%80%99s-groups

**Comment by AlexeyGirin** [comment]
@savinovava - расписать подробнее

**Comment by savinovava** [comment]
outdated
