### ISSUE TITLE
[5pt][US-7-2] Edit locator dialog

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn#358]
see design
Fields:
- Name: text field, check if unique
- Block type: select option
- Locator: check if locator is valid - TO BE DISCUSSED

[Related US-7-2](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2424884/Feature+list#US-7-2)

**Comment by AlexeyGirin** [comment]
Решили оставить пока Игорь что-то сделает

**Comment by MariiaNebesnova** [comment]
после jdi-testing/jdn#369

**Comment by savinovava** [comment]
[4pt] - front
[1pt] - QA

**Comment by MariiaNebesnova** [comment]
с @AlexeyGirin и @mariia-tokarchuk решили: дропдаун пока оставляем системным, будет стилизован в рамках jdi-testing/jdn#95

**Comment by MariiaNebesnova** [comment]
3.0.87

**Comment by pulya-na-vullet** [comment]
JDN v 3.0.88
Back-end v 2021-11-26-14.32.52
Функционал работает. Задачу на разработки и тестинг закрываю, есть смежный баг:
1. jdi-testing/jdn-ai#297
