### ISSUE TITLE
[0.5pt][US-3-1] Rework perception threshold section

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn#359]
according to design

[Related US-3-1](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2424884/Feature+list#US-3-1)

**Comment by MariiaNebesnova** [comment]
+ заменить десятичную дробь на процент

**Comment by savinovava** [comment]
Необходимо проверить соовтетствие с дизайном perception
[0.5pt] -QA

**Comment by MariiaNebesnova** [comment]
3.0.68

**Comment by pulya-na-vullet** [comment]
Дизайн соответствует Figma
JDN v 3.0.75
Back-end v 2021-11-01-06.14.14
Определение локаторов корректное.
