### ISSUE TITLE
Создать SoW проекта

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn#360]
Описать коцепцию проекта

- [x] Описать функциональность продукта на основе созданных Epics
- [x] Описать нефункциональные требования проекта
- [x] Описать таймлан проекта
- [x] Описать критерии успешности проекта

**Comment by savinovava** [comment]
The page link: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/65832/SoW+Statement+of+Work#2.2-Platform

**Comment by AlexeyGirin** [comment]
Done.
