### ISSUE TITLE
[US-13-1] Многостраничная генерация

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#364]
В данный момент - существующий дизайн (ещё не заимплеменченый, но уже вполне понятно, что скоро он будет) расчитан на герерацию одного пэйдж объекта с одной странички
При этом - у сайта может быть больше одной странички и для каждой - потребуется создать свой пэйдж объект и выгрузить потом это - в один тестовый проект (не файл как сейчас, а архив файлов в котором все они лежат в составе проекта)

[Related US-13-1](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2424884/Feature+list#US-13-1)

**Comment by mariia-tokarchuk** [comment]
Путь пользователя для многостраничной генерации:

**1) открывает плагин и страницу, по которой нужно сгенерировать Page Object**

![1](https://user-images.githubusercontent.com/89466817/145054176-9036a8c5-9fa4-4e57-808f-c286ca2b511e.png)



**2) кликает кнопку "New page object"** (при этом подтягивается автоматически url и title страницы) **и далее кнопку "Generate locators".**

Также на этом этапе есть возможность:
- открыть другую страницу для генерации, просто перейдя на нее на сайте; 
- изменить дефолтные настройки;

### ![2](https://user-images.githubusercontent.com/89466817/145054218-368d3c38-a042-4d08-87fa-9498941c9a9d.png)



**3) происходит автогенерация локаторов. Пользователь выбирает локаторы, которые ему необходимы для Page Object и нажимает кнопку "Confirm"**

(на этом шаге сохраняется вся функциональность, которая присутствовала в MVP)

![3](https://user-images.githubusercontent.com/89466817/145054246-4cb2f61f-efbe-42b5-9278-fdee5a3d375d.png)



**4) плагин возвращает пользователя снова на главную страницу, и он видит сформированный Page Object с выбранными локаторами.**

Также на этом этапе есть возможность:
- нагенерировать еще Page Object-ов;
- создать пакеты Page Object-ов;
- удалить;
- скачать;
- возле каждого Page Object, Package и локатора присутствует контекстное меню (которое позволяет произвести действия с элементом).

![4](https://user-images.githubusercontent.com/89466817/145054285-3683d248-d783-401d-b424-8e7bed6a1b93.png)

**Comment by mariia-tokarchuk** [comment]
Многостраничная генерация позволяет пользователю самостоятельно определять какая структура проекта ему будет удобнее, распределять все Page Object по Package и давать удобные названия.

**Например, вот такой набор Page Object-ов в пределах тестовой странички** 
![structure example](https://user-images.githubusercontent.com/89466817/145063141-5705dadc-bd18-4c4c-b7b4-5aea5eff0e81.png)

**Comment by mariia-tokarchuk** [comment]
Общая ссылка на Figma:
https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(New)?node-id=0%3A1

Также ссылка на новый дизайн добавлена в Confluence:
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2261362/UI+UX+design#UI%2FUX-Design-for-the-next-release

**Comment by AlexeyGirin** [comment]
Готово. Можно приступать к девелопменту
