### ISSUE TITLE
[0.5pt][US-6-7] Add Stop and Re-run locator generation options

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn#368]
#373 should be implemented
add this option to:
- [x] Locator list header
- [x] highlight element context menu
- [x] list item context menu

[Related US-6-7](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2424884/Feature+list#US-6-7)

**Comment by MariiaNebesnova** [comment]
3.0.66

**Comment by savinovava** [comment]
[0.5pt] - QA

**Comment by lisatatarinova** [comment]
tested, ok
