### ISSUE TITLE
[1.5pt][US-5-1] Implement Download warning dialog

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn#369]
see mockups: https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN?node-id=1144%3A96999

**Comment by savinovava** [comment]
[1pt] - front
[0.5pt] - QA

**Comment by pulya-na-vullet** [comment]
Done, the task contains no problems

**Comment by pulya-na-vullet** [comment]
![image](https://user-images.githubusercontent.com/61897393/141422553-e19a1a70-58af-4bc1-b874-b9f48ecabbe2.png)

Find one bug -> black color text for button [Cancel]. Backeground have black color too.

**Comment by pulya-na-vullet** [comment]
@MariiaNebesnova  https://mail.ru/

**Comment by pulya-na-vullet** [comment]
Task done< dont't have any problems
