### ISSUE TITLE
[2,5pt][US-11-1]Hover-over с именем компонента: Имя и тип не апдетятся после изменения

### ISSUE THREAD

**Issue by lisatatarinova** [jdi-testing/jdn#371]
JDN включен
JDN v 3.0.54
Back-end v 2021-09-07-09.37.43
https://jdi-testing.github.io/jdi-light/complex-table.html

1. Нажала Identify 
2. Навела курсор на компонент "text-field"
**Result:** 
            Name: text-field
            Type: text-field
3. Изменила имя компонента на 1231
4. Изменила тип компонента на Checkbox
5. Снова навела кусор на компонент.
**Actual result:**
![image](https://user-images.githubusercontent.com/34272388/135442946-e8eaa3f7-60ab-4b2a-a3e6-fd08f065d295.png)
**Expected result:** 
                        Name: 1231
                        Type: Checkbox

**Comment by savinovava** [comment]
[0.5pt] - QA
2pt - fe

**Comment by lisatatarinova** [comment]
@MariiaNebesnova test failed, баг на месте

**Comment by MariiaNebesnova** [comment]
3.0.73

**Comment by savinovava** [comment]
@MariiaNebesnova укажи pt, затраченные на разработку, пожалуйста, в комментариях
@lisatatarinova оцени, пожалуйста, в комментариях

2pt=1 рабочий день

**Comment by lisatatarinova** [comment]
заблокировано багом #389

**Comment by lisatatarinova** [comment]
заблокировано багом https://github.com/jdi-testing/jdn-ai/issues/83

**Comment by lisatatarinova** [comment]
test passed
