### ISSUE TITLE
[US-14-1] Разбиение на секции

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#372]
Описание странички одним пэйдж объектом (жава классом) несёт в себе недостаток - часто на страницах встречается группа элементов (меню, хеадер, футер) которые являются общими для всех странич.
В этом случае - страницу надо разбивать на составные части - секции, которые нужно описывать отдельными пэйдж объектами.
Необходимо придумать механнику работы которая поможет пользователю сделать такое разделение визуально.

[Related US-14-1](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2424884/Feature+list#US-14-1)

**Comment by savinovava** [comment]
US-14-1 **As a** user
**I want to** get page object for the group of elements (section)
**So that** I will have a quick access to the code of section

**Comment by mariia-tokarchuk** [comment]
Разбиение на секции происходит аналогично многостраничной генерации, описанной в таске - 
https://github.com/jdi-testing/jdn/issues/364 . 

При этом:
- на странице с генерацией локаторов пользователь выбирает только те локаторы, которые ему необходимы для конкретной секции. 
- пользователь может вручную переименовать PageObject на нужное название секции (до или после генерации).
- пользователь, дополнительно, может создать пакет, например, Section и туда помещать PageObject-ы, которые были сгенерированы для секций.

**Например, таким образом:**

<img width="1238" alt="Screenshot 2021-12-07 at 18 27 53" src="https://user-images.githubusercontent.com/89466817/145067904-5609cb64-e21d-4ff6-b409-ad30518563fd.png">

**Comment by mariia-tokarchuk** [comment]
Общая ссылка на Figma:
https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(New)?node-id=0%3A1

Также ссылка на новый дизайн добавлена в Confluence:
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2261362/UI+UX+design#UI%2FUX-Design-for-the-next-release

**Comment by AlexeyGirin** [comment]
Готово. Можно приступать к девелопменту
