### ISSUE TITLE
[1pt] [US-6-1]Компоненты после генерации уходят в статус Deleted или виснут в Waiting for generation

### ISSUE THREAD

**Issue by lisatatarinova** [jdi-testing/jdn#379]
JDN v 3.0.66
Back-end v 2021-09-28-08.31.54

1. Открыть web-site https://material-kit-react.devias.io/app/customers
2. Открыть JDN
3. Нажать Identify

Далее два разных варианта результатов (нестабильный баг)

_**Вариант 1.**_
**Actual result:** Часть компонентов зависает в waiting for generation (я ждала 2-3 мин)
![image](https://user-images.githubusercontent.com/34272388/139879979-92a1bb0c-b081-462a-bfc4-55300bbd05dd.png)
![image](https://user-images.githubusercontent.com/34272388/139880047-d230523f-2863-46a8-bb4b-2c3988dcaf50.png)

_**Вариант 2.**_
**Actual result:** Пару секунд (up to 15) локаторы гостят в waiting for generation, потом кочуют в Deleted
![image](https://user-images.githubusercontent.com/34272388/139880233-ab383c32-5e22-4910-8987-d7665451e1dd.png)

**Expected result:** Все локаторы идентифицированы, waiting to generation статус задерживается максимум на 30 сек (+-), все идентифицированные локаторы сгенерированы

**Comment by lisatatarinova** [comment]
QA 1pt

**Comment by MariiaNebesnova** [comment]
ждем кейс для воспроизведения

**Comment by lisatatarinova** [comment]
сайт, на котором был тест, уже не доступен.
на других сайтах то же поведение не обнаруживается
