### ISSUE TITLE
Верстка разъезжается после идентификации локаторов при маленькой ширине экрана

### ISSUE THREAD

**Issue by lisatatarinova** [jdi-testing/jdn#381]
JDN v 3.0.66
Back-end v 2021-09-28-08.31.54

Actual result:
![image](https://user-images.githubusercontent.com/34272388/140882005-1370b77f-1a7d-4317-8d83-5a1dd50a06aa.png)

Expected result: все красивенько и не перекрывает друг друга :)

**Comment by MariiaNebesnova** [comment]
duplicates https://github.com/jdi-testing/jdn-ai/issues/51

**Comment by lisatatarinova** [comment]
test passed 3.0.88
