### ISSUE TITLE
[task for discussion]  UI problems

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn#384]
test environment: google chrome 95.0.4638.54
plugin jdn;
1. Discussion:
![image](https://user-images.githubusercontent.com/61897393/141734652-5da323c5-6baa-43c2-b68d-5dc3f89dedfb.png)

2. Discussion:
![image](https://user-images.githubusercontent.com/61897393/141734775-dad59f71-fb61-40b2-8140-1eae43ff1e73.png)

3. Discussion:
![image](https://user-images.githubusercontent.com/61897393/141734825-952b96fe-0b84-410b-a5eb-1d56ef14e2dd.png)

4. Discussion:
![image](https://user-images.githubusercontent.com/61897393/141734875-7d3928d0-b5e8-428b-9a81-2ea1b9d4a7ce.png)

**Comment by AlexeyGirin** [comment]
1. Завести задачу на Машу Т.
2. Провести доп. проверку пикселей
3. Завести таску на удаление статуса через некоторое (10 секунд) время
4. В будущем спрячем

**Comment by AlexeyGirin** [comment]
Done,
