### ISSUE TITLE
[1pt][Locator list] It is necessary to close the free space if the user does not click [Generate]

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn#385]
We need to come up with a new display mechanism for a free field. In the current implementation, we always provide an empty field.
![image](https://user-images.githubusercontent.com/61897393/141936228-c47d51b9-6fc8-4659-bacf-ab7694ce0283.png)

Parent task:
https://github.com/jdi-testing/jdn/issues/384

**Comment by Dashnik** [comment]
Баг пофикшен. Доступен для тестирования в 3.0.83 и выше.

**Comment by pulya-na-vullet** [comment]
Plugin version JDN v 3.0.83
Back-end v 2021-11-01-06.14.14

bug doesn't repeat

https://user-images.githubusercontent.com/61897393/143183549-91b71eca-3605-43fc-9109-86f5aec4d529.mp4

.
