### ISSUE TITLE
[1pt][Locators generation is successfully completed]  need close this functionally  after 10 s 

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn#386]
After 10 seconds before locator list successful generated need close "Locators generation is successfully completed".
![image](https://user-images.githubusercontent.com/61897393/141937335-a500920b-c759-4d17-81fd-a6e8df8e96ae.png)

**Comment by Dashnik** [comment]
Проблема пофикшена в 3.0.82 билде.

**Comment by pulya-na-vullet** [comment]
Plugin version JDN v 3.0.83
Back-end v 2021-11-01-06.14.14

bug doesn't repeat

https://user-images.githubusercontent.com/61897393/143183728-9236b0f8-42b2-47d9-91c7-58ebcebc0276.mp4
