### ISSUE TITLE
[1pt][US-6-6][Download] After downloading, the button becomes transparent.

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn#387]
Версия 95.0.4638.69 (Официальная сборка), (64 бит)
site: mail.ru
plugin: JDN v 3.0.75
Back-end: 2021-11-01-06.14.14
Steps:
1. Open site
2. Open JDN plugin
3. Click [Identify]
4. Delete one active xpath element (locator)
5. Click [Download]

ER:
Button [Download] doesn't change color after click 
AR:
Button [Download] change color after click 
![image](https://user-images.githubusercontent.com/61897393/141986338-9a50a990-abba-4333-ab84-58641b90bb41.png)

**Comment by MariiaNebesnova** [comment]
дублирует https://github.com/jdi-testing/jdn-ai/issues/51

**Comment by lisatatarinova** [comment]
test passed 3.0.88
