### ISSUE TITLE
[0.5pt][Delete locator] Dont showe loacator "4 locators deleted successfully!" when user press [Delete] button

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn#388]
JDN v 3.0.75
Back-end v 2021-11-01-06.14.14

1. Open plugin IDN
2. Press [Identify]
3. Select several lokators
4. Press [Delete] button

ER: there is text "4 locators deleted successfully!" in locator list
AR: there is text "4 locators deleted successfully!" in locator list when user delete some several locators

![image](https://user-images.githubusercontent.com/61897393/142570539-6e7c74ab-8dc8-40b9-a7d5-44c567c4c079.png)

**Comment by Dashnik** [comment]
Это проблема не воспроизводится в v 3.0.85
![Notification](https://user-images.githubusercontent.com/35660327/143552045-32ca0519-2659-4fce-a737-abea23b7e232.gif)

**Comment by pulya-na-vullet** [comment]
Произвел ретест. Баг не воспроизводится
JDN v 3.0.88
Back-end v 2021-11-26-14.32.52
Версия 95.0.4638.69 (Официальная сборка), (x86_64)
<img width="1440" alt="Снимок экрана 2021-11-30 в 9 17 56 AM" src="https://user-images.githubusercontent.com/61897393/143995839-038576bc-336d-44b0-b212-d8dcdbd44b88.png">
.
