### ISSUE TITLE
[US-11-1][Medium] Marked up locators are visible on the new page

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn#391]
JDN v 3.1.157
Back-end v 2022-03-30-06.47.33
Chrome
https://onboarding.epam.com/#/dashboard

1) open the page
2) new page object
3) generate

AR = ER:
<img width="1318" alt="Screen Shot 2022-01-26 at 3 23 53 PM" src="https://user-images.githubusercontent.com/98175427/151162576-ba6ef7e5-8eba-458f-8444-8c450d00e4c2.png">

4) click unmarked element, for example Completed

AR: marks of bottom elements are on the middle of the page
<img width="1318" alt="Screen Shot 2022-01-26 at 3 26 06 PM" src="https://user-images.githubusercontent.com/98175427/151162880-4a2435ee-8bf8-4ea6-84bd-59710c6f6693.png">

ER: marks should stay on their elements no matter what happened on the page

**Comment by savinovava** [comment]
Динамическая страница -> требует отдельных доработок, пока не поддерживаем
