### ISSUE TITLE
File without URLs is created via 'Export URLs' button

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn#90]
**TBD** The bug is floating and isn't localized at current moment

Actual result:
In some situation the file is created correctly but sometimes (often) the file doesn't contains needed URLs
The full content in this case is as follows:
```
{
	"urlsList": []
}
```

Expected result:
The file contains all needed URLs

UPD:
During testing there was exported a file which missed one of URLs >_<
The whole file looks like:
```
{
	"urlsList": [
		"https://epam.github.io/JDI/index.html",
		"https://epam.github.io/JDI/contacts.html"
	]
}
```
without 'Metal' page. I really don't know why.

**Comment by AlexeyGirin** [comment]
Не пофикшено. Очень редко воспроизодится.
